In [1]:
import pickle
import re
import pandas as pd
import numpy as np
from data import *
from bnMLP import *
import os
from torch.utils.data import TensorDataset, DataLoader, random_split

from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
import torch
from sklearn.svm import SVC
from sklearn.neighbors import NearestCentroid
from sklearn.metrics import roc_auc_score, pairwise_distances
from utils import *

In [2]:
GLOBAL_CUTOFFS = {}
for a, b in pd.read_csv('cutoffs.csv').values:
    GLOBAL_CUTOFFS[a] = b
    # break

COHORTS = ['Autoimmune: Other', 'Cancer: Other', 'HIV', 'Healthy Control',
           'IBD', 'Multiple Myeloma', 'Transplant']

In [3]:
# DIM = 2
# if DIM != 2:
#     with open(f'final_models_{DIM}d.pkl', 'rb') as f:
#         data = pickle.load(f)
# else:
#     with open(f'final_models.pkl', 'rb') as f:
#         data = pickle.load(f)
# INCLUDE_OTHERS = True

In [3]:
DIM = 2
with open(f'final_models_2d_pfizer_moderna.pkl', 'rb') as f:
        data = pickle.load(f)

INCLUDE_OTHERS = False

In [4]:
results_6_excel, results_8_excel = data['dict6'], data['dict8']

In [6]:
# DIM = 2
# if not os.path.exists(f'final_results_{DIM}d'):
#     os.makedirs(f'final_results_{DIM}d')

#### Post to Post by cohort

In [7]:

columns = []
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Sensitivity at {t} Specificity')
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Specificity at {t} Sensitivity')
columns = [
    'Low Responders Accuracy',
    'High Responders Accuracy',
    'Harmonic Mean',
    'AUC'
] + columns


split_pattern = r',\s*(?![^()]*\))'

records = []
for k, v in results_8_excel.items():
    parts = re.split(split_pattern, k)
    seed, cohort, task, setting, clf, coeffs, usage = parts
    records.append({
        'seed': int(seed),
        'cohort': cohort,
        'task': task,
        'setting': setting,
        'clf': clf,
        'coeffs': coeffs,
        'usage': usage,
        **{name: val for name, val in zip(columns, v[-1])}
    })

df = pd.DataFrame(records)

group_cols = ['cohort', 'task', 'setting', 'clf', 'coeffs', 'usage']
metric_cols = columns

agg_df = df.groupby(group_cols)[metric_cols].agg(['mean', 'std']).reset_index()
agg_df.columns = ['_'.join(col).strip('_') for col in agg_df.columns.values]

# print(agg_df)

In [8]:
agg_df.head()

,cohort,task,setting,clf,coeffs,usage,Low Responders Accuracy_mean,Low Responders Accuracy_std,High Responders Accuracy_mean,High Responders Accuracy_std,...,Specificity at 0.75 Sensitivity_mean,Specificity at 0.75 Sensitivity_std,Specificity at 0.8 Sensitivity_mean,Specificity at 0.8 Sensitivity_std,Specificity at 0.85 Sensitivity_mean,Specificity at 0.85 Sensitivity_std,Specificity at 0.9 Sensitivity_mean,Specificity at 0.9 Sensitivity_std,Specificity at 0.95 Sensitivity_mean,Specificity at 0.95 Sensitivity_std
0,Autoimmune: Other,8,binary,mlp,"(4, 1)",Ab raw,0.485667,0.423503,0.477286,0.419315,...,0.094308,0.073005,0.094308,0.073005,0.0,0.0,0.0,0.0,0.0,0.0
1,Autoimmune: Other,8,binary,mlp,"(4, 1)",Demographic,0.397000,0.409897,0.568341,0.418619,...,0.081231,0.077127,0.081231,0.077127,0.0,0.0,0.0,0.0,0.0,0.0
2,Autoimmune: Other,8,no-cutoff,mlp,"(4, 1)",Ab raw,0.512333,0.410378,0.470451,0.403229,...,0.088615,0.070725,0.088615,0.070725,0.0,0.0,0.0,0.0,0.0,0.0
3,Autoimmune: Other,8,no-cutoff,mlp,"(4, 1)",Demographic,0.408667,0.423592,0.570143,0.415725,...,0.091231,0.062817,0.091231,0.062817,0.0,0.0,0.0,0.0,0.0,0.0
4,Cancer: Other,8,binary,mlp,"(4, 1)",Ab raw,0.509000,0.436491,0.499158,0.438935,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
X, y , emb_list, real_size, encoder = load_6(binary=True, cutoffs=None, include_all_vaccines=INCLUDE_OTHERS)
counts = {}
for cohort in COHORTS:
    
    # idx = X[:, 0] == 'Healthy Control'
    idx = X[:, 0] == cohort
    
    all_low_count = (y[idx] == 0).astype(float).sum()
    all_high_count = (y[idx] == 1).astype(float).sum()
    print(all_low_count, all_high_count, cohort)
    counts[f'{cohort},Test_N_Low'] = all_low_count
    counts[f'{cohort},Train_N_Low'] = all_low_count
    counts[f'{cohort},Test_N_High'] = all_high_count
    counts[f'{cohort},Train_N_High'] = all_high_count
counts

13.0 67.0 Autoimmune: Other
8.0 95.0 Cancer: Other
14.0 68.0 HIV
21.0 462.0 Healthy Control
4.0 33.0 IBD
60.0 90.0 Multiple Myeloma
71.0 67.0 Transplant

{'Autoimmune: Other,Test_N_Low': 13.0,
 'Autoimmune: Other,Train_N_Low': 13.0,
 'Autoimmune: Other,Test_N_High': 67.0,
 'Autoimmune: Other,Train_N_High': 67.0,
 'Cancer: Other,Test_N_Low': 8.0,
 'Cancer: Other,Train_N_Low': 8.0,
 'Cancer: Other,Test_N_High': 95.0,
 'Cancer: Other,Train_N_High': 95.0,
 'HIV,Test_N_Low': 14.0,
 'HIV,Train_N_Low': 14.0,
 'HIV,Test_N_High': 68.0,
 'HIV,Train_N_High': 68.0,
 'Healthy Control,Test_N_Low': 21.0,
 'Healthy Control,Train_N_Low': 21.0,
 'Healthy Control,Test_N_High': 462.0,
 'Healthy Control,Train_N_High': 462.0,
 'IBD,Test_N_Low': 4.0,
 'IBD,Train_N_Low': 4.0,
 'IBD,Test_N_High': 33.0,
 'IBD,Train_N_High': 33.0,
 'Multiple Myeloma,Test_N_Low': 60.0,
 'Multiple Myeloma,Train_N_Low': 60.0,
 'Multiple Myeloma,Test_N_High': 90.0,
 'Multiple Myeloma,Train_N_High': 90.0,
 'Transplant,Test_N_Low': 71.0,
 'Transplant,Train_N_Low': 71.0,
 'Transplant,Test_N_High': 67.0,
 'Transplant,Train_N_High': 67.0}

In [10]:
agg_df['Train_Timepoint'] = 'Post-B'
agg_df['Test_Timepoint'] = 'Post-B'
agg_df['Test_Cohort'] = agg_df['cohort']
def update_usage(row, what):
    cohort = row['cohort']
    return counts[f'{cohort},{what}']

for what in ['Train_N_Low', 'Train_N_High', 'Test_N_High', 'Test_N_Low']:
    agg_df[what] = agg_df.apply(lambda z:update_usage(z, what=what), axis=1)
    
agg_df = agg_df.rename(columns={
    'cohort': 'Train_Cohort', 
    'clf': 'Classifier', 
    'AUC_mean': 'CV_AUC_Mean',
    'AUC_std': 'CV_AUC_SD',
    'Sensitivity at 0.8 Specificity_mean': 'CV_Sen_at_80_Spe_Mean',
    'Sensitivity at 0.8 Specificity_std': 'CV_Sen_at_80_Spe_SD',
    'Low Responders Accuracy_mean': 'CV_Acc_Low_Mean',
    'High Responders Accuracy_mean': 'CV_Acc_High_Mean',
    'Low Responders Accuracy_std': 'CV_Acc_Low_SD',
    'High Responders Accuracy_std': 'CV_Acc_High_SD',
})

def update_usage(row):
    usage = row['usage']
    setting = row['setting']
    
    # Case 1: if usage is "Ab raw"
    
    out = 'Ab_raw'
    
    # Case 2: if usage is "Demographic"
    if setting.strip().lower() == 'binary':
        out += '+ Ab_binary'
        
    if usage.strip().lower() == 'demographic':
        out += '+ demographic'
    
    # Case 3: modify further based on 'setting'
    
    if setting.strip().lower() == 'no-cutoff':
        # don't add anything
        pass
    
    return out

# Apply transformation
agg_df['Feature_Set'] = agg_df.apply(update_usage, axis=1)
out = agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier',	'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]
out

,Train_Timepoint,Train_Cohort,Train_N_Low,Train_N_High,Feature_Set,Test_Timepoint,Test_Cohort,Test_N_Low,Test_N_High,Classifier,CV_AUC_Mean,CV_AUC_SD,CV_Sen_at_80_Spe_Mean,CV_Sen_at_80_Spe_SD,CV_Acc_Low_Mean,CV_Acc_Low_SD,CV_Acc_High_Mean,CV_Acc_High_SD
0,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw+ Ab_binary,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.449757,0.092995,0.280000,0.141897,0.485667,0.423503,0.477286,0.419315
1,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw+ Ab_binary+ demographic,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.461796,0.082237,0.293667,0.131186,0.397000,0.409897,0.568341,0.418619
2,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.474082,0.088714,0.316667,0.129707,0.512333,0.410378,0.470451,0.403229
3,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw+ demographic,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.480610,0.088678,0.307333,0.153052,0.408667,0.423592,0.570143,0.415725
4,Post-B,Cancer: Other,8.0,95.0,Ab_raw+ Ab_binary,Post-B,Cancer: Other,8.0,95.0,mlp,0.510526,0.108290,0.341000,0.190743,0.509000,0.436491,0.499158,0.438935
5,Post-B,Cancer: Other,8.0,95.0,Ab_raw+ Ab_binary+ demographic,Post-B,Cancer: Other,8.0,95.0,mlp,0.514737,0.110284,0.328000,0.206500,0.424000,0.428321,0.580421,0.417285
6,Post-B,Cancer: Other,8.0,95.0,Ab_raw,Post-B,Cancer: Other,8.0,95.0,mlp,0.501421,0.104526,0.307000,0.179930,0.489000,0.431089,0.502211,0.424827
7,Post-B,Cancer: Other,8.0,95.0,Ab_raw+ demographic,Post-B,Cancer: Other,8.0,95.0,mlp,0.493895,0.106905,0.285000,0.194560,0.435000,0.431669,0.567263,0.424768
8,Post-B,HIV,14.0,68.0,Ab_raw+ Ab_binary,Post-B,HIV,14.0,68.0,mlp,0.637245,0.108346,0.517000,0.174496,0.580667,0.368367,0.527857,0.397689
9,Post-B,HIV,14.0,68.0,Ab_raw+ Ab_binary+ demographic,Post-B,HIV,14.0,68.0,mlp,0.616832,0.103440,0.476000,0.176770,0.502667,0.370418,0.605769,0.377987
10,Post-B,HIV,14.0,68.0,Ab_raw,Post-B,HIV,14.0,68.0,mlp,0.648790,0.110686,0.534000,0.154976,0.620000,0.333872,0.528560,0.382123
11,Post-B,HIV,14.0,68.0,Ab_raw+ demographic,Post-B,HIV,14.0,68.0,mlp,0.621590,0.097657,0.496667,0.170725,0.502000,0.369239,0.616791,0.376618
12,Post-B,Healthy Control,21.0,462.0,Ab_raw+ Ab_binary,Post-B,Healthy Control,21.0,462.0,mlp,0.748358,0.078324,0.633300,0.139603,0.587400,0.344242,0.618927,0.367220
13,Post-B,Healthy Control,21.0,462.0,Ab_raw+ Ab_binary+ demographic,Post-B,Healthy Control,21.0,462.0,mlp,0.775160,0.054476,0.677700,0.109902,0.601200,0.318025,0.652665,0.350987
14,Post-B,Healthy Control,21.0,462.0,Ab_raw,Post-B,Healthy Control,21.0,462.0,mlp,0.798478,0.080250,0.720300,0.149419,0.682100,0.304914,0.615456,0.363418
15,Post-B,Healthy Control,21.0,462.0,Ab_raw+ demographic,Post-B,Healthy Control,21.0,462.0,mlp,0.794255,0.081287,0.715300,0.161035,0.612200,0.326597,0.675073,0.338186
16,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw+ Ab_binary,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.729602,0.055616,0.609500,0.108149,0.661167,0.282049,0.593111,0.298969
17,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw+ Ab_binary+ demographic,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.722870,0.064716,0.604667,0.120000,0.630500,0.280482,0.617889,0.311875
18,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.728597,0.061188,0.616167,0.118716,0.706500,0.250128,0.556444,0.288196
19,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw+ demographic,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.708264,0.054416,0.579500,0.115588,0.625667,0.290133,0.608444,0.281934
20,Post-B,Transplant,71.0,67.0,Ab_raw+ Ab_binary,Post-B,Transplant,71.0,67.0,mlp,0.537949,0.045735,0.327343,0.080965,0.543305,0.341795,0.488121,0.342149
21,Post-B,Transplant,71.0,67.0,Ab_raw+ Ab_binary+ demographic,Post-B,Transplant,71.0,67.0,mlp,0.548869,0.053081,0.333333,0.104563,0.510019,0.346526,0.539055,0.350814
22,Post-B,Transplant,71.0,67.0,Ab_raw,Post-B,Transplant,71.0,67.0,mlp,0.518009,0.050237,0.282390,0.080722,0.577095,0.320593,0.442582,0.314589
23,Post-B,Transplant,71.0,67.0,Ab_raw+ demographic,Post-B,Transplant,71.0,67.0,mlp,0.521407,0.048271,0.305667,0.089920,0.504952,0.345947,0.517758,0.343034

In [11]:
out.to_csv(f'final_results_{DIM}d/model_performance_summary_v1_revised.csv')
out

,Train_Timepoint,Train_Cohort,Train_N_Low,Train_N_High,Feature_Set,Test_Timepoint,Test_Cohort,Test_N_Low,Test_N_High,Classifier,CV_AUC_Mean,CV_AUC_SD,CV_Sen_at_80_Spe_Mean,CV_Sen_at_80_Spe_SD,CV_Acc_Low_Mean,CV_Acc_Low_SD,CV_Acc_High_Mean,CV_Acc_High_SD
0,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw+ Ab_binary,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.449757,0.092995,0.280000,0.141897,0.485667,0.423503,0.477286,0.419315
1,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw+ Ab_binary+ demographic,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.461796,0.082237,0.293667,0.131186,0.397000,0.409897,0.568341,0.418619
2,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.474082,0.088714,0.316667,0.129707,0.512333,0.410378,0.470451,0.403229
3,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw+ demographic,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.480610,0.088678,0.307333,0.153052,0.408667,0.423592,0.570143,0.415725
4,Post-B,Cancer: Other,8.0,95.0,Ab_raw+ Ab_binary,Post-B,Cancer: Other,8.0,95.0,mlp,0.510526,0.108290,0.341000,0.190743,0.509000,0.436491,0.499158,0.438935
5,Post-B,Cancer: Other,8.0,95.0,Ab_raw+ Ab_binary+ demographic,Post-B,Cancer: Other,8.0,95.0,mlp,0.514737,0.110284,0.328000,0.206500,0.424000,0.428321,0.580421,0.417285
6,Post-B,Cancer: Other,8.0,95.0,Ab_raw,Post-B,Cancer: Other,8.0,95.0,mlp,0.501421,0.104526,0.307000,0.179930,0.489000,0.431089,0.502211,0.424827
7,Post-B,Cancer: Other,8.0,95.0,Ab_raw+ demographic,Post-B,Cancer: Other,8.0,95.0,mlp,0.493895,0.106905,0.285000,0.194560,0.435000,0.431669,0.567263,0.424768
8,Post-B,HIV,14.0,68.0,Ab_raw+ Ab_binary,Post-B,HIV,14.0,68.0,mlp,0.637245,0.108346,0.517000,0.174496,0.580667,0.368367,0.527857,0.397689
9,Post-B,HIV,14.0,68.0,Ab_raw+ Ab_binary+ demographic,Post-B,HIV,14.0,68.0,mlp,0.616832,0.103440,0.476000,0.176770,0.502667,0.370418,0.605769,0.377987
10,Post-B,HIV,14.0,68.0,Ab_raw,Post-B,HIV,14.0,68.0,mlp,0.648790,0.110686,0.534000,0.154976,0.620000,0.333872,0.528560,0.382123
11,Post-B,HIV,14.0,68.0,Ab_raw+ demographic,Post-B,HIV,14.0,68.0,mlp,0.621590,0.097657,0.496667,0.170725,0.502000,0.369239,0.616791,0.376618
12,Post-B,Healthy Control,21.0,462.0,Ab_raw+ Ab_binary,Post-B,Healthy Control,21.0,462.0,mlp,0.748358,0.078324,0.633300,0.139603,0.587400,0.344242,0.618927,0.367220
13,Post-B,Healthy Control,21.0,462.0,Ab_raw+ Ab_binary+ demographic,Post-B,Healthy Control,21.0,462.0,mlp,0.775160,0.054476,0.677700,0.109902,0.601200,0.318025,0.652665,0.350987
14,Post-B,Healthy Control,21.0,462.0,Ab_raw,Post-B,Healthy Control,21.0,462.0,mlp,0.798478,0.080250,0.720300,0.149419,0.682100,0.304914,0.615456,0.363418
15,Post-B,Healthy Control,21.0,462.0,Ab_raw+ demographic,Post-B,Healthy Control,21.0,462.0,mlp,0.794255,0.081287,0.715300,0.161035,0.612200,0.326597,0.675073,0.338186
16,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw+ Ab_binary,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.729602,0.055616,0.609500,0.108149,0.661167,0.282049,0.593111,0.298969
17,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw+ Ab_binary+ demographic,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.722870,0.064716,0.604667,0.120000,0.630500,0.280482,0.617889,0.311875
18,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.728597,0.061188,0.616167,0.118716,0.706500,0.250128,0.556444,0.288196
19,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw+ demographic,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.708264,0.054416,0.579500,0.115588,0.625667,0.290133,0.608444,0.281934
20,Post-B,Transplant,71.0,67.0,Ab_raw+ Ab_binary,Post-B,Transplant,71.0,67.0,mlp,0.537949,0.045735,0.327343,0.080965,0.543305,0.341795,0.488121,0.342149
21,Post-B,Transplant,71.0,67.0,Ab_raw+ Ab_binary+ demographic,Post-B,Transplant,71.0,67.0,mlp,0.548869,0.053081,0.333333,0.104563,0.510019,0.346526,0.539055,0.350814
22,Post-B,Transplant,71.0,67.0,Ab_raw,Post-B,Transplant,71.0,67.0,mlp,0.518009,0.050237,0.282390,0.080722,0.577095,0.320593,0.442582,0.314589
23,Post-B,Transplant,71.0,67.0,Ab_raw+ demographic,Post-B,Transplant,71.0,67.0,mlp,0.521407,0.048271,0.305667,0.089920,0.504952,0.345947,0.517758,0.343034

#### Post to Post All

In [12]:
columns = []
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Sensitivity at {t} Specificity')
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Specificity at {t} Sensitivity')
columns = [
    'Low Responders Accuracy',
    'High Responders Accuracy',
    'Harmonic Mean',
    'AUC'
] + columns
for k, v in results_6_excel.items():
    seed, _, setting, clf, __, usage = re.split(r',\s*(?![^()]*\))', k)


records = []
for k, v in results_6_excel.items():
    parts = re.split(split_pattern, k)
    seed, task, setting, clf, coeffs, usage = parts
    records.append({
        'seed': int(seed),
        'cohort': 'All',
        'task': task,
        'setting': setting,
        'clf': clf,
        'coeffs': coeffs,
        'usage': usage,
        **{name: val for name, val in zip(columns, v[-1])}
    })

df = pd.DataFrame(records)

group_cols = ['task', 'cohort', 'setting', 'clf', 'coeffs', 'usage']
metric_cols = columns

agg_df = df.groupby(group_cols)[metric_cols].agg(['mean', 'std']).reset_index()
agg_df.columns = ['_'.join(col).strip('_') for col in agg_df.columns.values]
agg_df

,task,cohort,setting,clf,coeffs,usage,Low Responders Accuracy_mean,Low Responders Accuracy_std,High Responders Accuracy_mean,High Responders Accuracy_std,...,Specificity at 0.75 Sensitivity_mean,Specificity at 0.75 Sensitivity_std,Specificity at 0.8 Sensitivity_mean,Specificity at 0.8 Sensitivity_std,Specificity at 0.85 Sensitivity_mean,Specificity at 0.85 Sensitivity_std,Specificity at 0.9 Sensitivity_mean,Specificity at 0.9 Sensitivity_std,Specificity at 0.95 Sensitivity_mean,Specificity at 0.95 Sensitivity_std
0,6,All,binary,mlp,"(4, 1)",Ab raw,0.632833,0.169865,0.704736,0.155503,...,0.611617,0.041377,0.542008,0.047219,0.441010,0.059989,0.285421,0.080644,0.140252,0.075731
1,6,All,binary,mlp,"(4, 1)",Demographic,0.664830,0.181179,0.739511,0.150849,...,0.705097,0.028814,0.639411,0.044512,0.549464,0.055762,0.430519,0.082741,0.208046,0.103733
2,6,All,no-cutoff,mlp,"(4, 1)",Ab raw,0.646656,0.173008,0.693785,0.160514,...,0.605086,0.042990,0.538718,0.053309,0.454452,0.054754,0.320273,0.072844,0.154864,0.084929
3,6,All,no-cutoff,mlp,"(4, 1)",Demographic,0.696300,0.164525,0.751581,0.123391,...,0.739252,0.032362,0.689086,0.038065,0.613180,0.048132,0.489095,0.070503,0.255653,0.107591

In [13]:
agg_df['Train_Timepoint'] = 'Post-B'
agg_df['Test_Timepoint'] = 'Post-B'
agg_df['Test_Cohort'] = 'All'


X, y , emb_list, real_size, encoder = load_6(binary=True, cutoffs=None, include_all_vaccines=INCLUDE_OTHERS)

counts = {}
# for cohort in COHORTS:
    
    # idx = X[:, 0] == 'Healthy Control'
    # idx = X[:, 0] == cohort
all_low_count = (y == 0).astype(float).sum()
all_high_count = (y == 1).astype(float).sum()
counts[f'Test_N_Low'] = all_low_count
counts[f'Train_N_Low'] = all_low_count
counts[f'Test_N_High'] = all_high_count
counts[f'Train_N_High'] = all_high_count


def update_usage(row, what):
    return counts[f'{what}']

# Apply transformation
for what in ['Train_N_Low', 'Train_N_High', 'Test_N_High', 'Test_N_Low']:
    agg_df[what] = agg_df.apply(lambda z:update_usage(z, what=what), axis=1)
    
agg_df = agg_df.rename(columns={
    'cohort': 'Train_Cohort', 
    'clf': 'Classifier', 
    'AUC_mean': 'CV_AUC_Mean',
    'AUC_std': 'CV_AUC_SD',
    'Sensitivity at 0.8 Specificity_mean': 'CV_Sen_at_80_Spe_Mean',
    'Sensitivity at 0.8 Specificity_std': 'CV_Sen_at_80_Spe_SD',
    'Low Responders Accuracy_mean': 'CV_Acc_Low_Mean',
    'High Responders Accuracy_mean': 'CV_Acc_High_Mean',
    'Low Responders Accuracy_std': 'CV_Acc_Low_SD',
    'High Responders Accuracy_std': 'CV_Acc_High_SD',
})

def update_usage(row):
    # Start with base usage name
    usage = row['usage']
    setting = row['setting']
    
    
    # Case 1: if usage is "Ab raw"
    
    out = 'Ab_raw'
    
    
    # Case 2: if usage is "Demographic"
    if setting.strip().lower() == 'binary':
        out += '+ Ab_binary'
        
    if usage.strip().lower() == 'demographic':
        out += '+ demographic'
    
    # Case 3: modify further based on 'setting'
    
    if setting.strip().lower() == 'no-cutoff':
        # don't add anything
        pass
    
    return out

# Apply transformation
agg_df['Feature_Set'] = agg_df.apply(update_usage, axis=1)
agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier', 'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]

,Train_Timepoint,Train_Cohort,Train_N_Low,Train_N_High,Feature_Set,Test_Timepoint,Test_Cohort,Test_N_Low,Test_N_High,Classifier,CV_AUC_Mean,CV_AUC_SD,CV_Sen_at_80_Spe_Mean,CV_Sen_at_80_Spe_SD,CV_Acc_Low_Mean,CV_Acc_Low_SD,CV_Acc_High_Mean,CV_Acc_High_SD
0,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Post-B,All,191.0,882.0,mlp,0.744875,0.018760,0.577605,0.032581,0.632833,0.169865,0.704736,0.155503
1,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Post-B,All,191.0,882.0,mlp,0.791616,0.016184,0.660881,0.034741,0.664830,0.181179,0.739511,0.150849
2,Post-B,All,191.0,882.0,Ab_raw,Post-B,All,191.0,882.0,mlp,0.748236,0.025778,0.576405,0.047525,0.646656,0.173008,0.693785,0.160514
3,Post-B,All,191.0,882.0,Ab_raw+ demographic,Post-B,All,191.0,882.0,mlp,0.811106,0.015861,0.694242,0.039249,0.696300,0.164525,0.751581,0.123391

In [14]:
out = agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier',	'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]
out.to_csv(f'final_results_{DIM}d/model_performance_summary_v2_revised.csv')

#### Post to Post from All to cohort

In [9]:
metrics = {}
# dim = 16
device = 'cuda' if torch.cuda.is_available() else 'cpu'
for_json = {}

for k, v in results_6_excel.items():
    seed, task, setting, clf, coeffs, usage = re.split(r',\s*(?![^()]*\))', k)
    
    seed = int(seed)
    if setting == 'binary':
        cutoffs = GLOBAL_CUTOFFS
    else:
        cutoffs = None

    if 'raw' in usage:
        use_cat = False
    else:
        use_cat = True
    X, y , emb_list, real_size, encoder = load_6(binary=True, cutoffs=cutoffs, include_all_vaccines=INCLUDE_OTHERS)
    if use_cat:
            start_from = len(emb_list)
    else:
        start_from = 11
        
        
    
    
    size = real_size if use_cat else real_size - 1
    
    en = {}
    for k_cohort, v_cohort in (X[:, [0, 5]]):
        en[k_cohort] = v_cohort
     
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    
    
    for_stratify = y
    for fold, (train_idx, test_idx) in enumerate(skf.split(X, for_stratify), start=0):
        #################################################### Dataset
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]
        
        
        X_train_tensor = torch.from_numpy(X_train[:, start_from:].astype(np.float32))
        y_train_tensor = torch.from_numpy(y_train).float()
        
        X_test_tensor = torch.from_numpy(X_test[:, start_from:].astype(np.float32))
        y_test_tensor = torch.from_numpy(y_test).float()
        
        
        train_idx, val_idx = train_test_split(
            np.arange(len(X_train_tensor)),
            test_size=0.2,
            stratify=y_train_tensor.numpy() ,
            random_state=seed
        )
        
        # create datasets
        train_dataset = TensorDataset(X_train_tensor[train_idx], y_train_tensor[train_idx])
        val_dataset   = TensorDataset(X_train_tensor[val_idx],  y_train_tensor[val_idx])
        
        # data loaders
        train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True, generator=torch.Generator().manual_seed(seed))
        val_loader   = DataLoader(val_dataset,   batch_size=len(val_dataset), shuffle=False)
        test_loader = DataLoader(TensorDataset(X_test_tensor, y_test_tensor),
                                 batch_size=len(X_test_tensor), shuffle=False)
        
        m = BottleneckMLP(emb_list, size, start_from, 8, (128, 64, DIM), p=0.2, use_cat=use_cat, binary=True).to(device)
        
        m.load_state_dict(v[0][fold])
        
        
        for cohort in en.keys():
            for x_batch, y_batch in test_loader:
                pass
            
            index = X_test[:, 5] == en[cohort]
            
            
            
            if (y_batch[index] == 0).float().sum() < 1:
                print(cohort, fold, seed, 'not enough negative samples')
                continue
            if clf == 'mlp':
                with torch.no_grad():
                    m.eval()
                    logits, two_d = m(x_batch[index].to(device))
            else:
                with torch.no_grad():
                    x_for_clf = []
                    y_for_clf = []
                    for x_batch_train, y_batch_train in train_loader:
                        with torch.no_grad():
                            m.eval()
                            _, two_d = m(x_batch_train.to(device))
                        x_for_clf.extend(two_d)
                        y_for_clf.extend(y_batch_train)
                x_for_clf = torch.stack(x_for_clf).cpu().numpy()
                y_for_clf = torch.stack(y_for_clf).cpu().numpy()
                if clf == 'svm':
                    one = (y_for_clf == 1).astype(float).sum()
                    zero = (y_for_clf == 0).astype(float).sum()
                    w = (one/zero)
                    delta = 1
        
                    classifier = SVC(kernel="rbf", class_weight={0: w, 1: 1}, probability=True)
                    classifier.fit(x_for_clf, y_for_clf)
                    with torch.no_grad():
                        m.eval()
                        x_in = m(x_batch[index].to(device))[-1].cpu().numpy()
                    logits = classifier.decision_function(x_in)
                elif clf == 'nc':
                    classifier = NearestCentroid(metric="euclidean")
                    classifier.fit(x_for_clf, y_for_clf)
                    with torch.no_grad():
                        m.eval()
                        x_in = m(x_batch[index].to(device))[-1].cpu().numpy()
                    logits = classifier.predict(x_in)

            if 1:
                if clf == 'mlp':
                    y_pred = (logits.reshape(-1) > 0.5).int().cpu()
                elif clf == 'svm':
                    y_pred = torch.from_numpy(logits >= delta).int()
                elif clf == 'nc':
                    
                    y_pred = torch.from_numpy(logits).int()
                a_test = (y_pred[y_batch[index]==0] == y_batch[index][y_batch[index]==0]).float().mean().item() + 1e-20
                b_test = (y_pred[y_batch[index]==1] == y_batch[index][y_batch[index]==1]).float().mean().item() + 1e-20
                c_test = 2 / ((1/a_test) + 1/b_test)
                if clf == 'svm':
                    logits = torch.sigmoid(torch.from_numpy(logits))
                elif clf == 'nc':
                    D = pairwise_distances(x_in, classifier.centroids_, metric=classifier.metric)
                    pos_idx = np.where(classifier.classes_ == 1)[0][0]
                    logits = torch.from_numpy(-D[:, pos_idx])
                    
                # print(y_batch[index].shape, logits.shape, seed, fold, cohort)
                for_json[f'{seed}, {fold}, {cohort}'] = y_batch[index].cpu().numpy().tolist(), logits.cpu().numpy().reshape(-1).tolist()
                # raise
                try:
                    auc_test = roc_auc_score(y_batch[index].cpu().numpy(), logits.cpu().numpy())
                except:
                    auc_test = None
                sen_test = []
                spec_test = []
                for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
                    sen_, spec_ = at_95(logits.cpu().numpy(), y_batch[index], t=t)
                    sen_test.append(sen_)
                    spec_test.append(spec_)
                    
            
            metrics[f'{seed}, {fold}, {cohort}, {clf}, {setting}, {usage}'] = ([a_test, b_test, c_test, auc_test, *spec_test, *sen_test])                        
    
        # print('-----------------')

IBD 0 0 not enough negative samples
IBD 1 0 not enough negative samples
IBD 3 0 not enough negative samples
IBD 0 0 not enough negative samples
IBD 1 0 not enough negative samples
IBD 3 0 not enough negative samples
IBD 0 0 not enough negative samples
IBD 1 0 not enough negative samples
IBD 3 0 not enough negative samples
IBD 0 0 not enough negative samples
IBD 1 0 not enough negative samples
IBD 3 0 not enough negative samples
Cancer: Other 0 1 not enough negative samples
Cancer: Other 1 1 not enough negative samples
IBD 1 1 not enough negative samples
IBD 4 1 not enough negative samples
Cancer: Other 0 1 not enough negative samples
Cancer: Other 1 1 not enough negative samples
IBD 1 1 not enough negative samples
IBD 4 1 not enough negative samples
Cancer: Other 0 1 not enough negative samples
Cancer: Other 1 1 not enough negative samples
IBD 1 1 not enough negative samples
IBD 4 1 not enough negative samples
Cancer: Other 0 1 not enough negative samples
Cancer: Other 1 1 not enough negative samples
IBD 1 1 not enough negative samples
IBD 4 1 not enough negative samples
IBD 0 2 not enough negative samples
Cancer: Other 1 2 not enough negative samples
IBD 0 2 not enough negative samples
Cancer: Other 1 2 not enough negative samples
IBD 0 2 not enough negative samples
Cancer: Other 1 2 not enough negative samples
IBD 0 2 not enough negative samples
Cancer: Other 1 2 not enough negative samples
Autoimmune: Other 1 3 not enough negative samples
Cancer: Other 1 3 not enough negative samples
IBD 2 3 not enough negative samples
Cancer: Other 4 3 not enough negative samples
Autoimmune: Other 1 3 not enough negative samples
Cancer: Other 1 3 not enough negative samples
IBD 2 3 not enough negative samples
Cancer: Other 4 3 not enough negative samples
Autoimmune: Other 1 3 not enough negative samples
Cancer: Other 1 3 not enough negative samples
IBD 2 3 not enough negative samples
Cancer: Other 4 3 not enough negative samples
Autoimmune: Other 1 3 not enough negative samples
Cancer: Other 1 3 not enough negative samples
IBD 2 3 not enough negative samples
Cancer: Other 4 3 not enough negative samples
Autoimmune: Other 1 4 not enough negative samples
IBD 1 4 not enough negative samples
IBD 2 4 not enough negative samples
Autoimmune: Other 1 4 not enough negative samples
IBD 1 4 not enough negative samples
IBD 2 4 not enough negative samples
Autoimmune: Other 1 4 not enough negative samples
IBD 1 4 not enough negative samples
IBD 2 4 not enough negative samples
Autoimmune: Other 1 4 not enough negative samples
IBD 1 4 not enough negative samples
IBD 2 4 not enough negative samples
IBD 0 5 not enough negative samples
IBD 1 5 not enough negative samples
Cancer: Other 2 5 not enough negative samples
IBD 4 5 not enough negative samples
IBD 0 5 not enough negative samples
IBD 1 5 not enough negative samples
Cancer: Other 2 5 not enough negative samples
IBD 4 5 not enough negative samples
IBD 0 5 not enough negative samples
IBD 1 5 not enough negative samples
Cancer: Other 2 5 not enough negative samples
IBD 4 5 not enough negative samples
IBD 0 5 not enough negative samples
IBD 1 5 not enough negative samples
Cancer: Other 2 5 not enough negative samples
IBD 4 5 not enough negative samples
IBD 2 6 not enough negative samples
IBD 4 6 not enough negative samples
IBD 2 6 not enough negative samples
IBD 4 6 not enough negative samples
IBD 2 6 not enough negative samples
IBD 4 6 not enough negative samples
IBD 2 6 not enough negative samples
IBD 4 6 not enough negative samples
IBD 1 7 not enough negative samples
IBD 2 7 not enough negative samples
IBD 1 7 not enough negative samples
IBD 2 7 not enough negative samples
IBD 1 7 not enough negative samples
IBD 2 7 not enough negative samples
IBD 1 7 not enough negative samples
IBD 2 7 not enough negative samples
IBD 0 8 not enough negative samples
Autoimmune: Other 1 8 not enough negative samples
Cancer: Other 4 8 not enough negative samples
IBD 4 8 not enough negative samples
IBD 0 8 not enough negative samples
Autoimmune: Other 1 8 not enough negative samples
Cancer: Other 4 8 not enough negative samples
IBD 4 8 not enough negative samples
IBD 0 8 not enough negative samples
Autoimmune: Other 1 8 not enough negative samples
Cancer: Other 4 8 not enough negative samples
IBD 4 8 not enough negative samples
IBD 0 8 not enough negative samples
Autoimmune: Other 1 8 not enough negative samples
Cancer: Other 4 8 not enough negative samples
IBD 4 8 not enough negative samples
Cancer: Other 0 9 not enough negative samples
IBD 3 9 not enough negative samples
IBD 4 9 not enough negative samples
Cancer: Other 0 9 not enough negative samples
IBD 3 9 not enough negative samples
IBD 4 9 not enough negative samples
Cancer: Other 0 9 not enough negative samples
IBD 3 9 not enough negative samples
IBD 4 9 not enough negative samples
Cancer: Other 0 9 not enough negative samples
IBD 3 9 not enough negative samples
IBD 4 9 not enough negative samples
HIV 1 10 not enough negative samples
IBD 2 10 not enough negative samples
HIV 1 10 not enough negative samples
IBD 2 10 not enough negative samples
HIV 1 10 not enough negative samples
IBD 2 10 not enough negative samples
HIV 1 10 not enough negative samples
IBD 2 10 not enough negative samples
IBD 1 11 not enough negative samples
IBD 3 11 not enough negative samples
IBD 1 11 not enough negative samples
IBD 3 11 not enough negative samples
IBD 1 11 not enough negative samples
IBD 3 11 not enough negative samples
IBD 1 11 not enough negative samples
IBD 3 11 not enough negative samples
IBD 1 12 not enough negative samples
Cancer: Other 2 12 not enough negative samples
Cancer: Other 3 12 not enough negative samples
IBD 1 12 not enough negative samples
Cancer: Other 2 12 not enough negative samples
Cancer: Other 3 12 not enough negative samples
IBD 1 12 not enough negative samples
Cancer: Other 2 12 not enough negative samples
Cancer: Other 3 12 not enough negative samples
IBD 1 12 not enough negative samples
Cancer: Other 2 12 not enough negative samples
Cancer: Other 3 12 not enough negative samples
IBD 2 13 not enough negative samples
Autoimmune: Other 3 13 not enough negative samples
IBD 2 13 not enough negative samples
Autoimmune: Other 3 13 not enough negative samples
IBD 2 13 not enough negative samples
Autoimmune: Other 3 13 not enough negative samples
IBD 2 13 not enough negative samples
Autoimmune: Other 3 13 not enough negative samples
IBD 0 14 not enough negative samples
IBD 1 14 not enough negative samples
IBD 2 14 not enough negative samples
Cancer: Other 3 14 not enough negative samples
Autoimmune: Other 4 14 not enough negative samples
IBD 0 14 not enough negative samples
IBD 1 14 not enough negative samples
IBD 2 14 not enough negative samples
Cancer: Other 3 14 not enough negative samples
Autoimmune: Other 4 14 not enough negative samples
IBD 0 14 not enough negative samples
IBD 1 14 not enough negative samples
IBD 2 14 not enough negative samples
Cancer: Other 3 14 not enough negative samples
Autoimmune: Other 4 14 not enough negative samples
IBD 0 14 not enough negative samples
IBD 1 14 not enough negative samples
IBD 2 14 not enough negative samples
Cancer: Other 3 14 not enough negative samples
Autoimmune: Other 4 14 not enough negative samples
IBD 0 15 not enough negative samples
IBD 2 15 not enough negative samples
HIV 4 15 not enough negative samples
IBD 0 15 not enough negative samples
IBD 2 15 not enough negative samples
HIV 4 15 not enough negative samples
IBD 0 15 not enough negative samples
IBD 2 15 not enough negative samples
HIV 4 15 not enough negative samples
IBD 0 15 not enough negative samples
IBD 2 15 not enough negative samples
HIV 4 15 not enough negative samples
IBD 0 16 not enough negative samples
IBD 2 16 not enough negative samples
IBD 0 16 not enough negative samples
IBD 2 16 not enough negative samples
IBD 0 16 not enough negative samples
IBD 2 16 not enough negative samples
IBD 0 16 not enough negative samples
IBD 2 16 not enough negative samples
Cancer: Other 0 17 not enough negative samples
IBD 1 17 not enough negative samples
HIV 2 17 not enough negative samples
IBD 3 17 not enough negative samples
IBD 4 17 not enough negative samples
Cancer: Other 0 17 not enough negative samples
IBD 1 17 not enough negative samples
HIV 2 17 not enough negative samples
IBD 3 17 not enough negative samples
IBD 4 17 not enough negative samples
Cancer: Other 0 17 not enough negative samples
IBD 1 17 not enough negative samples
HIV 2 17 not enough negative samples
IBD 3 17 not enough negative samples
IBD 4 17 not enough negative samples
Cancer: Other 0 17 not enough negative samples
IBD 1 17 not enough negative samples
HIV 2 17 not enough negative samples
IBD 3 17 not enough negative samples
IBD 4 17 not enough negative samples
IBD 0 18 not enough negative samples
Autoimmune: Other 2 18 not enough negative samples
IBD 3 18 not enough negative samples
Cancer: Other 4 18 not enough negative samples
IBD 0 18 not enough negative samples
Autoimmune: Other 2 18 not enough negative samples
IBD 3 18 not enough negative samples
Cancer: Other 4 18 not enough negative samples
IBD 0 18 not enough negative samples
Autoimmune: Other 2 18 not enough negative samples
IBD 3 18 not enough negative samples
Cancer: Other 4 18 not enough negative samples
IBD 0 18 not enough negative samples
Autoimmune: Other 2 18 not enough negative samples
IBD 3 18 not enough negative samples
Cancer: Other 4 18 not enough negative samples
IBD 3 19 not enough negative samples
IBD 4 19 not enough negative samples
IBD 3 19 not enough negative samples
IBD 4 19 not enough negative samples
IBD 3 19 not enough negative samples
IBD 4 19 not enough negative samples
IBD 3 19 not enough negative samples
IBD 4 19 not enough negative samples
Cancer: Other 1 20 not enough negative samples
IBD 2 20 not enough negative samples
IBD 3 20 not enough negative samples
HIV 4 20 not enough negative samples
Cancer: Other 1 20 not enough negative samples
IBD 2 20 not enough negative samples
IBD 3 20 not enough negative samples
HIV 4 20 not enough negative samples
Cancer: Other 1 20 not enough negative samples
IBD 2 20 not enough negative samples
IBD 3 20 not enough negative samples
HIV 4 20 not enough negative samples
Cancer: Other 1 20 not enough negative samples
IBD 2 20 not enough negative samples
IBD 3 20 not enough negative samples
HIV 4 20 not enough negative samples
IBD 0 21 not enough negative samples
Autoimmune: Other 2 21 not enough negative samples
Cancer: Other 4 21 not enough negative samples
IBD 0 21 not enough negative samples
Autoimmune: Other 2 21 not enough negative samples
Cancer: Other 4 21 not enough negative samples
IBD 0 21 not enough negative samples
Autoimmune: Other 2 21 not enough negative samples
Cancer: Other 4 21 not enough negative samples
IBD 0 21 not enough negative samples
Autoimmune: Other 2 21 not enough negative samples
Cancer: Other 4 21 not enough negative samples
IBD 2 22 not enough negative samples
Cancer: Other 3 22 not enough negative samples
HIV 4 22 not enough negative samples
IBD 4 22 not enough negative samples
IBD 2 22 not enough negative samples
Cancer: Other 3 22 not enough negative samples
HIV 4 22 not enough negative samples
IBD 4 22 not enough negative samples
IBD 2 22 not enough negative samples
Cancer: Other 3 22 not enough negative samples
HIV 4 22 not enough negative samples
IBD 4 22 not enough negative samples
IBD 2 22 not enough negative samples
Cancer: Other 3 22 not enough negative samples
HIV 4 22 not enough negative samples
IBD 4 22 not enough negative samples
IBD 1 23 not enough negative samples
Autoimmune: Other 3 23 not enough negative samples
IBD 4 23 not enough negative samples
IBD 1 23 not enough negative samples
Autoimmune: Other 3 23 not enough negative samples
IBD 4 23 not enough negative samples
IBD 1 23 not enough negative samples
Autoimmune: Other 3 23 not enough negative samples
IBD 4 23 not enough negative samples
IBD 1 23 not enough negative samples
Autoimmune: Other 3 23 not enough negative samples
IBD 4 23 not enough negative samples
Autoimmune: Other 0 24 not enough negative samples
IBD 1 24 not enough negative samples
Cancer: Other 3 24 not enough negative samples
Autoimmune: Other 0 24 not enough negative samples
IBD 1 24 not enough negative samples
Cancer: Other 3 24 not enough negative samples
Autoimmune: Other 0 24 not enough negative samples
IBD 1 24 not enough negative samples
Cancer: Other 3 24 not enough negative samples
Autoimmune: Other 0 24 not enough negative samples
IBD 1 24 not enough negative samples
Cancer: Other 3 24 not enough negative samples
Autoimmune: Other 0 25 not enough negative samples
IBD 1 25 not enough negative samples
IBD 3 25 not enough negative samples
Cancer: Other 4 25 not enough negative samples
IBD 4 25 not enough negative samples
Autoimmune: Other 0 25 not enough negative samples
IBD 1 25 not enough negative samples
IBD 3 25 not enough negative samples
Cancer: Other 4 25 not enough negative samples
IBD 4 25 not enough negative samples
Autoimmune: Other 0 25 not enough negative samples
IBD 1 25 not enough negative samples
IBD 3 25 not enough negative samples
Cancer: Other 4 25 not enough negative samples
IBD 4 25 not enough negative samples
Autoimmune: Other 0 25 not enough negative samples
IBD 1 25 not enough negative samples
IBD 3 25 not enough negative samples
Cancer: Other 4 25 not enough negative samples
IBD 4 25 not enough negative samples
IBD 1 26 not enough negative samples
IBD 2 26 not enough negative samples
IBD 1 26 not enough negative samples
IBD 2 26 not enough negative samples
IBD 1 26 not enough negative samples
IBD 2 26 not enough negative samples
IBD 1 26 not enough negative samples
IBD 2 26 not enough negative samples
IBD 2 27 not enough negative samples
Autoimmune: Other 3 27 not enough negative samples
IBD 4 27 not enough negative samples
IBD 2 27 not enough negative samples
Autoimmune: Other 3 27 not enough negative samples
IBD 4 27 not enough negative samples
IBD 2 27 not enough negative samples
Autoimmune: Other 3 27 not enough negative samples
IBD 4 27 not enough negative samples
IBD 2 27 not enough negative samples
Autoimmune: Other 3 27 not enough negative samples
IBD 4 27 not enough negative samples
IBD 0 28 not enough negative samples
IBD 4 28 not enough negative samples
IBD 0 28 not enough negative samples
IBD 4 28 not enough negative samples
IBD 0 28 not enough negative samples
IBD 4 28 not enough negative samples
IBD 0 28 not enough negative samples
IBD 4 28 not enough negative samples
IBD 2 29 not enough negative samples
HIV 3 29 not enough negative samples
IBD 3 29 not enough negative samples
IBD 2 29 not enough negative samples
HIV 3 29 not enough negative samples
IBD 3 29 not enough negative samples
IBD 2 29 not enough negative samples
HIV 3 29 not enough negative samples
IBD 3 29 not enough negative samples
IBD 2 29 not enough negative samples
HIV 3 29 not enough negative samples
IBD 3 29 not enough negative samples
IBD 0 30 not enough negative samples
IBD 2 30 not enough negative samples
IBD 4 30 not enough negative samples
IBD 0 30 not enough negative samples
IBD 2 30 not enough negative samples
IBD 4 30 not enough negative samples
IBD 0 30 not enough negative samples
IBD 2 30 not enough negative samples
IBD 4 30 not enough negative samples
IBD 0 30 not enough negative samples
IBD 2 30 not enough negative samples
IBD 4 30 not enough negative samples
IBD 2 31 not enough negative samples
Cancer: Other 3 31 not enough negative samples
IBD 3 31 not enough negative samples
Cancer: Other 4 31 not enough negative samples
IBD 2 31 not enough negative samples
Cancer: Other 3 31 not enough negative samples
IBD 3 31 not enough negative samples
Cancer: Other 4 31 not enough negative samples
IBD 2 31 not enough negative samples
Cancer: Other 3 31 not enough negative samples
IBD 3 31 not enough negative samples
Cancer: Other 4 31 not enough negative samples
IBD 2 31 not enough negative samples
Cancer: Other 3 31 not enough negative samples
IBD 3 31 not enough negative samples
Cancer: Other 4 31 not enough negative samples
IBD 1 32 not enough negative samples
Cancer: Other 2 32 not enough negative samples
IBD 3 32 not enough negative samples
IBD 1 32 not enough negative samples
Cancer: Other 2 32 not enough negative samples
IBD 3 32 not enough negative samples
IBD 1 32 not enough negative samples
Cancer: Other 2 32 not enough negative samples
IBD 3 32 not enough negative samples
IBD 1 32 not enough negative samples
Cancer: Other 2 32 not enough negative samples
IBD 3 32 not enough negative samples
IBD 1 33 not enough negative samples
Autoimmune: Other 2 33 not enough negative samples
IBD 2 33 not enough negative samples
HIV 4 33 not enough negative samples
IBD 1 33 not enough negative samples
Autoimmune: Other 2 33 not enough negative samples
IBD 2 33 not enough negative samples
HIV 4 33 not enough negative samples
IBD 1 33 not enough negative samples
Autoimmune: Other 2 33 not enough negative samples
IBD 2 33 not enough negative samples
HIV 4 33 not enough negative samples
IBD 1 33 not enough negative samples
Autoimmune: Other 2 33 not enough negative samples
IBD 2 33 not enough negative samples
HIV 4 33 not enough negative samples
IBD 0 34 not enough negative samples
IBD 4 34 not enough negative samples
IBD 0 34 not enough negative samples
IBD 4 34 not enough negative samples
IBD 0 34 not enough negative samples
IBD 4 34 not enough negative samples
IBD 0 34 not enough negative samples
IBD 4 34 not enough negative samples
IBD 0 35 not enough negative samples
IBD 1 35 not enough negative samples
HIV 2 35 not enough negative samples
HIV 4 35 not enough negative samples
IBD 0 35 not enough negative samples
IBD 1 35 not enough negative samples
HIV 2 35 not enough negative samples
HIV 4 35 not enough negative samples
IBD 0 35 not enough negative samples
IBD 1 35 not enough negative samples
HIV 2 35 not enough negative samples
HIV 4 35 not enough negative samples
IBD 0 35 not enough negative samples
IBD 1 35 not enough negative samples
HIV 2 35 not enough negative samples
HIV 4 35 not enough negative samples
Cancer: Other 0 36 not enough negative samples
IBD 2 36 not enough negative samples
HIV 3 36 not enough negative samples
IBD 4 36 not enough negative samples
Cancer: Other 0 36 not enough negative samples
IBD 2 36 not enough negative samples
HIV 3 36 not enough negative samples
IBD 4 36 not enough negative samples
Cancer: Other 0 36 not enough negative samples
IBD 2 36 not enough negative samples
HIV 3 36 not enough negative samples
IBD 4 36 not enough negative samples
Cancer: Other 0 36 not enough negative samples
IBD 2 36 not enough negative samples
HIV 3 36 not enough negative samples
IBD 4 36 not enough negative samples
Cancer: Other 1 37 not enough negative samples
IBD 1 37 not enough negative samples
Cancer: Other 2 37 not enough negative samples
IBD 4 37 not enough negative samples
Cancer: Other 1 37 not enough negative samples
IBD 1 37 not enough negative samples
Cancer: Other 2 37 not enough negative samples
IBD 4 37 not enough negative samples
Cancer: Other 1 37 not enough negative samples
IBD 1 37 not enough negative samples
Cancer: Other 2 37 not enough negative samples
IBD 4 37 not enough negative samples
Cancer: Other 1 37 not enough negative samples
IBD 1 37 not enough negative samples
Cancer: Other 2 37 not enough negative samples
IBD 4 37 not enough negative samples
Autoimmune: Other 0 38 not enough negative samples
IBD 2 38 not enough negative samples
IBD 4 38 not enough negative samples
Autoimmune: Other 0 38 not enough negative samples
IBD 2 38 not enough negative samples
IBD 4 38 not enough negative samples
Autoimmune: Other 0 38 not enough negative samples
IBD 2 38 not enough negative samples
IBD 4 38 not enough negative samples
Autoimmune: Other 0 38 not enough negative samples
IBD 2 38 not enough negative samples
IBD 4 38 not enough negative samples
Cancer: Other 4 39 not enough negative samples
IBD 4 39 not enough negative samples

In [10]:
import json
with open("only_pfizer_moderna.json", "w") as f:
    json.dump(for_json, f)

In [16]:
columns = []
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Sensitivity at {t} Specificity')
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Specificity at {t} Sensitivity')
columns = [
    'Low Responders Accuracy',
    'High Responders Accuracy',
    'Harmonic Mean',
    'AUC'
] + columns



records = []
for k, v in metrics.items():
    seed, fold, cohort, clf, setting, usage = k.split(', ')
    records.append({
        'seed': int(seed),
        'fold': int(fold),
        'cohort': cohort,
        'setting': setting,
        'clf': clf,
        'usage': usage,
        **{name: val for name, val in zip(columns, v)}
    })

df = pd.DataFrame(records)

group_cols = ['cohort', 'setting', 'clf', 'usage']
metric_cols = columns

agg_df = df.groupby(group_cols)[metric_cols].agg(['mean', 'std']).reset_index()
agg_df.columns = ['_'.join(col).strip('_') for col in agg_df.columns.values]
agg_df

,cohort,setting,clf,usage,Low Responders Accuracy_mean,Low Responders Accuracy_std,High Responders Accuracy_mean,High Responders Accuracy_std,Harmonic Mean_mean,Harmonic Mean_std,...,Specificity at 0.75 Sensitivity_mean,Specificity at 0.75 Sensitivity_std,Specificity at 0.8 Sensitivity_mean,Specificity at 0.8 Sensitivity_std,Specificity at 0.85 Sensitivity_mean,Specificity at 0.85 Sensitivity_std,Specificity at 0.9 Sensitivity_mean,Specificity at 0.9 Sensitivity_std,Specificity at 0.95 Sensitivity_mean,Specificity at 0.95 Sensitivity_std
0,Autoimmune: Other,binary,mlp,Ab raw,0.431621,0.363343,0.722958,0.212234,0.407795,0.298522,...,0.136297,0.218472,0.129897,0.214435,0.045923,0.134000,0.004661,0.036517,0.000000,0.000000
1,Autoimmune: Other,binary,mlp,Demographic,0.353288,0.344949,0.734826,0.222734,0.343338,0.292806,...,0.121918,0.211502,0.112690,0.205316,0.039684,0.130597,0.000768,0.012609,0.000000,0.000000
2,Autoimmune: Other,no-cutoff,mlp,Ab raw,0.458967,0.351548,0.713129,0.207379,0.439941,0.291340,...,0.140478,0.227523,0.134309,0.223907,0.050374,0.150474,0.002760,0.039211,0.000000,0.000000
3,Autoimmune: Other,no-cutoff,mlp,Demographic,0.393217,0.366531,0.742100,0.222477,0.368663,0.303838,...,0.145185,0.236974,0.132422,0.227892,0.052533,0.152184,0.001914,0.019794,0.000000,0.000000
4,Cancer: Other,binary,mlp,Ab raw,0.285092,0.365937,0.792216,0.178355,0.280311,0.332474,...,0.060018,0.168548,0.059120,0.167820,0.006073,0.045291,0.000000,0.000000,0.000000,0.000000
5,Cancer: Other,binary,mlp,Demographic,0.333257,0.404452,0.809290,0.188842,0.307094,0.348930,...,0.067713,0.186658,0.064184,0.182180,0.009502,0.067423,0.000000,0.000000,0.000000,0.000000
6,Cancer: Other,no-cutoff,mlp,Ab raw,0.370566,0.397850,0.774441,0.187206,0.349409,0.343192,...,0.071743,0.187014,0.070596,0.186426,0.013210,0.085267,0.000191,0.003991,0.000000,0.000000
7,Cancer: Other,no-cutoff,mlp,Demographic,0.308219,0.402641,0.827871,0.176175,0.289032,0.357086,...,0.072504,0.196908,0.070757,0.194137,0.008870,0.065878,0.000191,0.003991,0.000000,0.000000
8,HIV,binary,mlp,Ab raw,0.607380,0.321267,0.651887,0.225512,0.533077,0.243505,...,0.197378,0.268341,0.180274,0.263478,0.083595,0.188169,0.008469,0.062664,0.000000,0.000000
9,HIV,binary,mlp,Demographic,0.624555,0.325839,0.663963,0.229486,0.542017,0.254889,...,0.191467,0.253901,0.176251,0.245012,0.094099,0.192510,0.013514,0.077135,0.000000,0.000000
10,HIV,no-cutoff,mlp,Ab raw,0.614647,0.329741,0.647280,0.225174,0.529673,0.253453,...,0.190596,0.267451,0.179733,0.262186,0.084874,0.195252,0.004783,0.036902,0.000000,0.000000
11,HIV,no-cutoff,mlp,Demographic,0.622535,0.327132,0.701061,0.220072,0.561934,0.255726,...,0.206573,0.279692,0.193509,0.274341,0.090660,0.204025,0.007649,0.061827,0.000000,0.000000
12,Healthy Control,binary,mlp,Ab raw,0.593101,0.307493,0.780503,0.156140,0.593765,0.235224,...,0.454786,0.316123,0.406219,0.311561,0.276853,0.305671,0.074452,0.182942,0.000000,0.000000
13,Healthy Control,binary,mlp,Demographic,0.467709,0.325577,0.863765,0.136335,0.512384,0.295308,...,0.459211,0.324443,0.416137,0.322431,0.286043,0.318922,0.085764,0.212283,0.000000,0.000000
14,Healthy Control,no-cutoff,mlp,Ab raw,0.680785,0.287889,0.769881,0.160984,0.656571,0.200654,...,0.486316,0.321275,0.445558,0.317819,0.319498,0.324224,0.089323,0.208983,0.000000,0.000000
15,Healthy Control,no-cutoff,mlp,Demographic,0.502072,0.314168,0.903390,0.093574,0.569346,0.288638,...,0.481072,0.342368,0.425267,0.336230,0.305983,0.329544,0.081504,0.203073,0.000000,0.000000
16,IBD,binary,mlp,Ab raw,0.604377,0.464740,0.670807,0.250843,0.445870,0.366144,...,0.013195,0.085145,0.013195,0.085145,0.002020,0.034816,0.000000,0.000000,0.000000,0.000000
17,IBD,binary,mlp,Demographic,0.553872,0.476648,0.735585,0.250556,0.421396,0.384606,...,0.015376,0.093018,0.015376,0.093018,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,IBD,no-cutoff,mlp,Ab raw,0.555275,0.463432,0.655131,0.265510,0.398174,0.356931,...,0.009444,0.066808,0.009444,0.066808,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,IBD,no-cutoff,mlp,Demographic,0.416667,0.471703,0.754203,0.260446,0.309555,0.373844,...,0.006371,0.057151,0.006371,0.057151,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,Multiple Myeloma,binary,mlp,Ab raw,0.832532,0.169517,0.383451,0.234819,0.456451,0.195596,...,0.440341,0.186469,0.382507,0.185224,0.318109,0.186240,0.203841,0.178015,0.120658,0.156128
21,Multiple Myeloma,binary,mlp,Demographic,0.838487,0.177868,0.352270,0.260336,0.409239,0.229125,...,0.420693,0.194919,0.362161,0.194608,0.298613,0.189284,0.192038,0.166819,0.124867,0.159629
22,Multiple Myeloma,no-cutoff,mlp,Ab raw,0.821854,0.179769,0.399928,0.242977,0.464556,0.201860,...,0.449979,0.199733,0.381477,0.199862,0.303051,0.198424,0.195351,0.176832,0.121262,0.155283
23,Multiple Myeloma,no-cutoff,mlp,Demographic,0.857137,0.156632,0.306166,0.267978,0.362121,0.262986,...,0.418615,0.207480,0.368731,0.207545,0.296124,0.210572,0.177771,0.179844,0.111460,0.160835
24,Transplant,binary,mlp,Ab raw,0.560823,0.235393,0.541231,0.241908,0.455505,0.148296,...,0.293277,0.171973,0.239335,0.172862,0.168852,0.164509,0.078535,0.117767,0.038724,0.090405
25,Transplant,binary,mlp,Demographic,0.691742,0.241177,0.391836,0.250248,0.395972,0.182477,...,0.292073,0.172853,0.238483,0.165246,0.184711,0.156517,0.116447,0.138654,0.066269,0.119591
26,Transplant,no-cutoff,mlp,Ab raw,0.570291,0.240952,0.502334,0.247491,0.433385,0.145966,...,0.265692,0.161573,0.218009,0.152977,0.160680,0.143682,0.090056,0.117018,0.041507,0.084221
27,Transplant,no-cutoff,mlp,Demographic,0.757807,0.219936,0.287391,0.229401,0.325795,0.194949,...,0.250456,0.157365,0.211869,0.152810,0.160612,0.142260,0.102471,0.127275,0.054653,0.096664

In [17]:
X, y , emb_list, real_size, encoder = load_6(binary=True, cutoffs=None, include_all_vaccines=INCLUDE_OTHERS)
counts = {}
for cohort in COHORTS:
    
    
    all_low_count_train = (y == 0).astype(float).sum()
    all_high_count_train = (y == 1).astype(float).sum()
    idx = X[:, 0] == cohort
    all_low_count = (y[idx] == 0).astype(float).sum()
    all_high_count = (y[idx] == 1).astype(float).sum()
    counts[f'{cohort},Test_N_Low'] = all_low_count
    counts[f'All,Train_N_Low'] = all_low_count_train
    counts[f'{cohort},Test_N_High'] = all_high_count
    counts[f'All,Train_N_High'] = all_high_count_train
counts

{'Autoimmune: Other,Test_N_Low': 13.0,
 'All,Train_N_Low': 191.0,
 'Autoimmune: Other,Test_N_High': 67.0,
 'All,Train_N_High': 882.0,
 'Cancer: Other,Test_N_Low': 8.0,
 'Cancer: Other,Test_N_High': 95.0,
 'HIV,Test_N_Low': 14.0,
 'HIV,Test_N_High': 68.0,
 'Healthy Control,Test_N_Low': 21.0,
 'Healthy Control,Test_N_High': 462.0,
 'IBD,Test_N_Low': 4.0,
 'IBD,Test_N_High': 33.0,
 'Multiple Myeloma,Test_N_Low': 60.0,
 'Multiple Myeloma,Test_N_High': 90.0,
 'Transplant,Test_N_Low': 71.0,
 'Transplant,Test_N_High': 67.0}

In [18]:
agg_df['Train_Timepoint'] = 'Post-B'
agg_df['Test_Timepoint'] = 'Post-B'

agg_df['Test_Cohort'] = agg_df['cohort']
agg_df['Train_Cohort'] = 'All'



def update_usage(row, what):
    cohort = row['cohort']
    try:
        return counts[f'{cohort},{what}']
    except:
        return counts[f'All,{what}']

# Apply transformation
for what in ['Train_N_Low', 'Train_N_High', 'Test_N_High', 'Test_N_Low']:
    agg_df[what] = agg_df.apply(lambda z:update_usage(z, what=what), axis=1)
    
    
agg_df = agg_df.rename(columns={
    # 'cohort': 'Train_Cohort', 
    'clf': 'Classifier', 
    'AUC_mean': 'CV_AUC_Mean',
    'AUC_std': 'CV_AUC_SD',
    'Sensitivity at 0.8 Specificity_mean': 'CV_Sen_at_80_Spe_Mean',
    'Sensitivity at 0.8 Specificity_std': 'CV_Sen_at_80_Spe_SD',
    'Low Responders Accuracy_mean': 'CV_Acc_Low_Mean',
    'High Responders Accuracy_mean': 'CV_Acc_High_Mean',
    'Low Responders Accuracy_std': 'CV_Acc_Low_SD',
    'High Responders Accuracy_std': 'CV_Acc_High_SD',
})

def update_usage(row):
    # Start with base usage name
    usage = row['usage']
    setting = row['setting']
    
    
    # Case 1: if usage is "Ab raw"
    
    out = 'Ab_raw'
    
    
    # Case 2: if usage is "Demographic"
    if setting.strip().lower() == 'binary':
        out += '+ Ab_binary'
        
    if usage.strip().lower() == 'demographic':
        out += '+ demographic'
    
    # Case 3: modify further based on 'setting'
    
    if setting.strip().lower() == 'no-cutoff':
        # don't add anything
        pass
    
    return out

# Apply transformation
agg_df['Feature_Set'] = agg_df.apply(update_usage, axis=1)
agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier', 'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]

,Train_Timepoint,Train_Cohort,Train_N_Low,Train_N_High,Feature_Set,Test_Timepoint,Test_Cohort,Test_N_Low,Test_N_High,Classifier,CV_AUC_Mean,CV_AUC_SD,CV_Sen_at_80_Spe_Mean,CV_Sen_at_80_Spe_SD,CV_Acc_Low_Mean,CV_Acc_Low_SD,CV_Acc_High_Mean,CV_Acc_High_SD
0,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.610635,0.214982,0.505486,0.340363,0.431621,0.363343,0.722958,0.212234
1,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.575000,0.215141,0.449032,0.332622,0.353288,0.344949,0.734826,0.222734
2,Post-B,All,191.0,882.0,Ab_raw,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.621011,0.222646,0.516160,0.335118,0.458967,0.351548,0.713129,0.207379
3,Post-B,All,191.0,882.0,Ab_raw+ demographic,Post-B,Autoimmune: Other,13.0,67.0,mlp,0.611201,0.221918,0.498931,0.353172,0.393217,0.366531,0.742100,0.222477
4,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Post-B,Cancer: Other,8.0,95.0,mlp,0.594958,0.239413,0.451529,0.401213,0.285092,0.365937,0.792216,0.178355
5,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Post-B,Cancer: Other,8.0,95.0,mlp,0.618499,0.250598,0.497133,0.410009,0.333257,0.404452,0.809290,0.188842
6,Post-B,All,191.0,882.0,Ab_raw,Post-B,Cancer: Other,8.0,95.0,mlp,0.628388,0.234860,0.496713,0.408290,0.370566,0.397850,0.774441,0.187206
7,Post-B,All,191.0,882.0,Ab_raw+ demographic,Post-B,Cancer: Other,8.0,95.0,mlp,0.638044,0.244798,0.526529,0.412771,0.308219,0.402641,0.827871,0.176175
8,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Post-B,HIV,14.0,68.0,mlp,0.696008,0.200384,0.601369,0.316498,0.607380,0.321267,0.651887,0.225512
9,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Post-B,HIV,14.0,68.0,mlp,0.711270,0.194798,0.627665,0.306480,0.624555,0.325839,0.663963,0.229486
10,Post-B,All,191.0,882.0,Ab_raw,Post-B,HIV,14.0,68.0,mlp,0.702408,0.205915,0.608492,0.319261,0.614647,0.329741,0.647280,0.225174
11,Post-B,All,191.0,882.0,Ab_raw+ demographic,Post-B,HIV,14.0,68.0,mlp,0.729830,0.187144,0.672354,0.295704,0.622535,0.327132,0.701061,0.220072
12,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Post-B,Healthy Control,21.0,462.0,mlp,0.788137,0.133507,0.710137,0.238206,0.593101,0.307493,0.780503,0.156140
13,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Post-B,Healthy Control,21.0,462.0,mlp,0.784919,0.133595,0.721437,0.238496,0.467709,0.325577,0.863765,0.136335
14,Post-B,All,191.0,882.0,Ab_raw,Post-B,Healthy Control,21.0,462.0,mlp,0.823718,0.125446,0.746351,0.235463,0.680785,0.287889,0.769881,0.160984
15,Post-B,All,191.0,882.0,Ab_raw+ demographic,Post-B,Healthy Control,21.0,462.0,mlp,0.822972,0.125130,0.775677,0.213128,0.502072,0.314168,0.903390,0.093574
16,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Post-B,IBD,4.0,33.0,mlp,0.743733,0.243794,0.706229,0.415936,0.604377,0.464740,0.670807,0.250843
17,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Post-B,IBD,4.0,33.0,mlp,0.741632,0.237683,0.691919,0.430860,0.553872,0.476648,0.735585,0.250556
18,Post-B,All,191.0,882.0,Ab_raw,Post-B,IBD,4.0,33.0,mlp,0.675833,0.246570,0.561167,0.460631,0.555275,0.463432,0.655131,0.265510
19,Post-B,All,191.0,882.0,Ab_raw+ demographic,Post-B,IBD,4.0,33.0,mlp,0.690738,0.249524,0.609428,0.456330,0.416667,0.471703,0.754203,0.260446
20,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.693706,0.099367,0.490321,0.246949,0.832532,0.169517,0.383451,0.234819
21,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.695757,0.103780,0.487269,0.273520,0.838487,0.177868,0.352270,0.260336
22,Post-B,All,191.0,882.0,Ab_raw,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.693804,0.113758,0.501017,0.252578,0.821854,0.179769,0.399928,0.242977
23,Post-B,All,191.0,882.0,Ab_raw+ demographic,Post-B,Multiple Myeloma,60.0,90.0,mlp,0.683446,0.113940,0.479234,0.274624,0.857137,0.156632,0.306166,0.267978
24,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Post-B,Transplant,71.0,67.0,mlp,0.580288,0.099595,0.376505,0.169004,0.560823,0.235393,0.541231,0.241908
25,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Post-B,Transplant,71.0,67.0,mlp,0.580701,0.112564,0.353151,0.218116,0.691742,0.241177,0.391836,0.250248
26,Post-B,All,191.0,882.0,Ab_raw,Post-B,Transplant,71.0,67.0,mlp,0.558172,0.102923,0.340592,0.174302,0.570291,0.240952,0.502334,0.247491
27,Post-B,All,191.0,882.0,Ab_raw+ demographic,Post-B,Transplant,71.0,67.0,mlp,0.544560,0.105767,0.278724,0.197590,0.757807,0.219936,0.287391,0.229401

In [19]:
out = agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier',	'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]
out.to_csv(f'final_results_{DIM}d/model_performance_summary_v3_revised.csv')

#### Post to Pre from All to cohort

In [20]:
metrics = {}

for k, v in results_6_excel.items():
    
    seed, task, setting, clf, coeffs, usage = re.split(r',\s*(?![^()]*\))', k)
    seed = int(seed)
    if setting == 'binary':
        cutoffs = GLOBAL_CUTOFFS
    else:
        cutoffs = None

    if 'raw' in usage:
        use_cat = False
    else:
        use_cat = True
    if use_cat:
            start_from = len(emb_list)
    else:
        start_from = 11
        
    
    X6, y6 , pid6, emb_list6, real_size6, encoder6 = load_6(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)
    
    X2, y2 , pid2, emb_list2, real_size2, encoder2 = load_2(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)
    
    size = real_size6 if use_cat else real_size6 - 1
    
    en = {}
    for k_cohort, v_cohort in (X6[:, [0, 5]]):
        en[k_cohort] = v_cohort
     
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    
    
    for_stratify = y6
    for fold, (train_idx, test_idx) in enumerate(skf.split(X6, for_stratify), start=0):
        
        index = np.isin(pid2, pid6[test_idx])
        
        X_train = X6[train_idx]
        y_train = y6[train_idx]
        X_test = X2[index]
        y_test = y2[index]
        
        #################################################### Dataset
        
        X_train_tensor = torch.from_numpy(X_train[:, start_from:].astype(np.float32))
        y_train_tensor = torch.from_numpy(y_train).float()
        
        X_test_tensor = torch.from_numpy(X_test[:, start_from:].astype(np.float32))
        y_test_tensor = torch.from_numpy(y_test).float()
        
        
        # stratified split using sklearn
        train_idx, val_idx = train_test_split(
            np.arange(len(X_train_tensor)),
            test_size=0.2,
            stratify=y_train_tensor.numpy() ,
            random_state=seed
        )
        
        # create datasets
        train_dataset = TensorDataset(X_train_tensor[train_idx], y_train_tensor[train_idx])
        val_dataset   = TensorDataset(X_train_tensor[val_idx],  y_train_tensor[val_idx])
        
        # data loaders
        train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True, generator=torch.Generator().manual_seed(seed))
        val_loader   = DataLoader(val_dataset,   batch_size=len(val_dataset), shuffle=False)
        test_loader = DataLoader(TensorDataset(X_test_tensor, y_test_tensor),
                                 batch_size=len(X_test_tensor), shuffle=False)
        m = BottleneckMLP(emb_list, size, start_from, 8, (128, 64, DIM), p=0.2, use_cat=use_cat, binary=True).to(device)
        m.load_state_dict(v[0][fold])
        
        
        for cohort in en.keys():
            for x_batch, y_batch in test_loader:
                pass
            
            index = X_test[:, 5] == en[cohort]
            
            if (y_batch[index] == 0).float().sum() < 1:
                print(cohort, fold, seed, 'not enough negative samples')
                continue
            if clf == 'mlp':
                with torch.no_grad():
                    m.eval()
                    logits, two_d = m(x_batch[index].to(device))
            else:
                with torch.no_grad():
                    x_for_clf = []
                    y_for_clf = []
                    for x_batch_train, y_batch_train in train_loader:
                        with torch.no_grad():
                            m.eval()
                            _, two_d = m(x_batch_train.to(device))
                        x_for_clf.extend(two_d)
                        y_for_clf.extend(y_batch_train)
                x_for_clf = torch.stack(x_for_clf).cpu().numpy()
                y_for_clf = torch.stack(y_for_clf).cpu().numpy()
                if clf == 'svm':
                    one = (y_for_clf == 1).astype(float).sum()
                    zero = (y_for_clf == 0).astype(float).sum()
                    w = (one/zero)
                    delta = 1
        
                    classifier = SVC(kernel="rbf", class_weight={0: w, 1: 1}, probability=True)
                    classifier.fit(x_for_clf, y_for_clf)
                    with torch.no_grad():
                        m.eval()
                        x_in = m(x_batch[index].to(device))[-1].cpu().numpy()
                    logits = classifier.decision_function(x_in)
                elif clf == 'nc':
                    classifier = NearestCentroid(metric="euclidean")
                    classifier.fit(x_for_clf, y_for_clf)
                    with torch.no_grad():
                        m.eval()
                        x_in = m(x_batch[index].to(device))[-1].cpu().numpy()
                    logits = classifier.predict(x_in)

            if 1:
                if clf == 'mlp':
                    y_pred = (logits.reshape(-1) > 0.5).int().cpu()
                elif clf == 'svm':
                    y_pred = torch.from_numpy(logits >= delta).int()
                elif clf == 'nc':
                    
                    y_pred = torch.from_numpy(logits).int()
                a_test = (y_pred[y_batch[index]==0] == y_batch[index][y_batch[index]==0]).float().mean().item() + 1e-20
                b_test = (y_pred[y_batch[index]==1] == y_batch[index][y_batch[index]==1]).float().mean().item() + 1e-20
                c_test = 2 / ((1/a_test) + 1/b_test)
                if clf == 'svm':
                    logits = torch.sigmoid(torch.from_numpy(logits))
                elif clf == 'nc':
                    D = pairwise_distances(x_in, classifier.centroids_, metric=classifier.metric)
                    pos_idx = np.where(classifier.classes_ == 1)[0][0]
                    logits = torch.from_numpy(-D[:, pos_idx])
                    # logits = torch.sigmoid(torch.from_numpy(logits))

                try:
                    auc_test = roc_auc_score(y_batch[index].cpu().numpy(), logits.cpu().numpy())
                except:
                    auc_test = None
                sen_test = []
                spec_test = []
                for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
                    sen_, spec_ = at_95(logits.cpu().numpy(), y_batch[index], t=t)
                    sen_test.append(sen_)
                    spec_test.append(spec_)
                    
            
            metrics[f'{seed}, {fold}, {cohort}, {clf}, {setting}, {usage}'] = ([a_test, b_test, c_test, auc_test, *spec_test, *sen_test])

IBD 0 0 not enough negative samples
IBD 1 0 not enough negative samples
Cancer: Other 2 0 not enough negative samples
Cancer: Other 3 0 not enough negative samples
IBD 3 0 not enough negative samples
IBD 0 0 not enough negative samples
IBD 1 0 not enough negative samples
Cancer: Other 2 0 not enough negative samples
Cancer: Other 3 0 not enough negative samples
IBD 3 0 not enough negative samples
IBD 0 0 not enough negative samples
IBD 1 0 not enough negative samples
Cancer: Other 2 0 not enough negative samples
Cancer: Other 3 0 not enough negative samples
IBD 3 0 not enough negative samples
IBD 0 0 not enough negative samples
IBD 1 0 not enough negative samples
Cancer: Other 2 0 not enough negative samples
Cancer: Other 3 0 not enough negative samples
IBD 3 0 not enough negative samples
Cancer: Other 0 1 not enough negative samples
Cancer: Other 1 1 not enough negative samples
IBD 1 1 not enough negative samples
Cancer: Other 2 1 not enough negative samples
IBD 3 1 not enough negative samples
IBD 4 1 not enough negative samples
Cancer: Other 0 1 not enough negative samples
Cancer: Other 1 1 not enough negative samples
IBD 1 1 not enough negative samples
Cancer: Other 2 1 not enough negative samples
IBD 3 1 not enough negative samples
IBD 4 1 not enough negative samples
Cancer: Other 0 1 not enough negative samples
Cancer: Other 1 1 not enough negative samples
IBD 1 1 not enough negative samples
Cancer: Other 2 1 not enough negative samples
IBD 3 1 not enough negative samples
IBD 4 1 not enough negative samples
Cancer: Other 0 1 not enough negative samples
Cancer: Other 1 1 not enough negative samples
IBD 1 1 not enough negative samples
Cancer: Other 2 1 not enough negative samples
IBD 3 1 not enough negative samples
IBD 4 1 not enough negative samples
Cancer: Other 0 2 not enough negative samples
IBD 0 2 not enough negative samples
Cancer: Other 1 2 not enough negative samples
IBD 3 2 not enough negative samples
Cancer: Other 0 2 not enough negative samples
IBD 0 2 not enough negative samples
Cancer: Other 1 2 not enough negative samples
IBD 3 2 not enough negative samples
Cancer: Other 0 2 not enough negative samples
IBD 0 2 not enough negative samples
Cancer: Other 1 2 not enough negative samples
IBD 3 2 not enough negative samples
Cancer: Other 0 2 not enough negative samples
IBD 0 2 not enough negative samples
Cancer: Other 1 2 not enough negative samples
IBD 3 2 not enough negative samples
Autoimmune: Other 1 3 not enough negative samples
Cancer: Other 1 3 not enough negative samples
IBD 2 3 not enough negative samples
Cancer: Other 4 3 not enough negative samples
IBD 4 3 not enough negative samples
Autoimmune: Other 1 3 not enough negative samples
Cancer: Other 1 3 not enough negative samples
IBD 2 3 not enough negative samples
Cancer: Other 4 3 not enough negative samples
IBD 4 3 not enough negative samples
Autoimmune: Other 1 3 not enough negative samples
Cancer: Other 1 3 not enough negative samples
IBD 2 3 not enough negative samples
Cancer: Other 4 3 not enough negative samples
IBD 4 3 not enough negative samples
Autoimmune: Other 1 3 not enough negative samples
Cancer: Other 1 3 not enough negative samples
IBD 2 3 not enough negative samples
Cancer: Other 4 3 not enough negative samples
IBD 4 3 not enough negative samples
Autoimmune: Other 1 4 not enough negative samples
IBD 1 4 not enough negative samples
IBD 2 4 not enough negative samples
Autoimmune: Other 1 4 not enough negative samples
IBD 1 4 not enough negative samples
IBD 2 4 not enough negative samples
Autoimmune: Other 1 4 not enough negative samples
IBD 1 4 not enough negative samples
IBD 2 4 not enough negative samples
Autoimmune: Other 1 4 not enough negative samples
IBD 1 4 not enough negative samples
IBD 2 4 not enough negative samples
IBD 0 5 not enough negative samples
IBD 1 5 not enough negative samples
Autoimmune: Other 2 5 not enough negative samples
Cancer: Other 2 5 not enough negative samples
Cancer: Other 4 5 not enough negative samples
IBD 4 5 not enough negative samples
IBD 0 5 not enough negative samples
IBD 1 5 not enough negative samples
Autoimmune: Other 2 5 not enough negative samples
Cancer: Other 2 5 not enough negative samples
Cancer: Other 4 5 not enough negative samples
IBD 4 5 not enough negative samples
IBD 0 5 not enough negative samples
IBD 1 5 not enough negative samples
Autoimmune: Other 2 5 not enough negative samples
Cancer: Other 2 5 not enough negative samples
Cancer: Other 4 5 not enough negative samples
IBD 4 5 not enough negative samples
IBD 0 5 not enough negative samples
IBD 1 5 not enough negative samples
Autoimmune: Other 2 5 not enough negative samples
Cancer: Other 2 5 not enough negative samples
Cancer: Other 4 5 not enough negative samples
IBD 4 5 not enough negative samples
Cancer: Other 0 6 not enough negative samples
IBD 2 6 not enough negative samples
IBD 3 6 not enough negative samples
IBD 4 6 not enough negative samples
Cancer: Other 0 6 not enough negative samples
IBD 2 6 not enough negative samples
IBD 3 6 not enough negative samples
IBD 4 6 not enough negative samples
Cancer: Other 0 6 not enough negative samples
IBD 2 6 not enough negative samples
IBD 3 6 not enough negative samples
IBD 4 6 not enough negative samples
Cancer: Other 0 6 not enough negative samples
IBD 2 6 not enough negative samples
IBD 3 6 not enough negative samples
IBD 4 6 not enough negative samples
IBD 1 7 not enough negative samples
IBD 2 7 not enough negative samples
Cancer: Other 3 7 not enough negative samples
IBD 4 7 not enough negative samples
IBD 1 7 not enough negative samples
IBD 2 7 not enough negative samples
Cancer: Other 3 7 not enough negative samples
IBD 4 7 not enough negative samples
IBD 1 7 not enough negative samples
IBD 2 7 not enough negative samples
Cancer: Other 3 7 not enough negative samples
IBD 4 7 not enough negative samples
IBD 1 7 not enough negative samples
IBD 2 7 not enough negative samples
Cancer: Other 3 7 not enough negative samples
IBD 4 7 not enough negative samples
IBD 0 8 not enough negative samples
Autoimmune: Other 1 8 not enough negative samples
Cancer: Other 4 8 not enough negative samples
IBD 4 8 not enough negative samples
IBD 0 8 not enough negative samples
Autoimmune: Other 1 8 not enough negative samples
Cancer: Other 4 8 not enough negative samples
IBD 4 8 not enough negative samples
IBD 0 8 not enough negative samples
Autoimmune: Other 1 8 not enough negative samples
Cancer: Other 4 8 not enough negative samples
IBD 4 8 not enough negative samples
IBD 0 8 not enough negative samples
Autoimmune: Other 1 8 not enough negative samples
Cancer: Other 4 8 not enough negative samples
IBD 4 8 not enough negative samples
Cancer: Other 0 9 not enough negative samples
IBD 3 9 not enough negative samples
IBD 4 9 not enough negative samples
Cancer: Other 0 9 not enough negative samples
IBD 3 9 not enough negative samples
IBD 4 9 not enough negative samples
Cancer: Other 0 9 not enough negative samples
IBD 3 9 not enough negative samples
IBD 4 9 not enough negative samples
Cancer: Other 0 9 not enough negative samples
IBD 3 9 not enough negative samples
IBD 4 9 not enough negative samples
HIV 1 10 not enough negative samples
IBD 1 10 not enough negative samples
IBD 2 10 not enough negative samples
Cancer: Other 3 10 not enough negative samples
HIV 1 10 not enough negative samples
IBD 1 10 not enough negative samples
IBD 2 10 not enough negative samples
Cancer: Other 3 10 not enough negative samples
HIV 1 10 not enough negative samples
IBD 1 10 not enough negative samples
IBD 2 10 not enough negative samples
Cancer: Other 3 10 not enough negative samples
HIV 1 10 not enough negative samples
IBD 1 10 not enough negative samples
IBD 2 10 not enough negative samples
Cancer: Other 3 10 not enough negative samples
Cancer: Other 0 11 not enough negative samples
IBD 1 11 not enough negative samples
IBD 3 11 not enough negative samples
Cancer: Other 0 11 not enough negative samples
IBD 1 11 not enough negative samples
IBD 3 11 not enough negative samples
Cancer: Other 0 11 not enough negative samples
IBD 1 11 not enough negative samples
IBD 3 11 not enough negative samples
Cancer: Other 0 11 not enough negative samples
IBD 1 11 not enough negative samples
IBD 3 11 not enough negative samples
IBD 1 12 not enough negative samples
Cancer: Other 2 12 not enough negative samples
IBD 2 12 not enough negative samples
Cancer: Other 3 12 not enough negative samples
IBD 1 12 not enough negative samples
Cancer: Other 2 12 not enough negative samples
IBD 2 12 not enough negative samples
Cancer: Other 3 12 not enough negative samples
IBD 1 12 not enough negative samples
Cancer: Other 2 12 not enough negative samples
IBD 2 12 not enough negative samples
Cancer: Other 3 12 not enough negative samples
IBD 1 12 not enough negative samples
Cancer: Other 2 12 not enough negative samples
IBD 2 12 not enough negative samples
Cancer: Other 3 12 not enough negative samples
IBD 2 13 not enough negative samples
Autoimmune: Other 3 13 not enough negative samples
IBD 4 13 not enough negative samples
IBD 2 13 not enough negative samples
Autoimmune: Other 3 13 not enough negative samples
IBD 4 13 not enough negative samples
IBD 2 13 not enough negative samples
Autoimmune: Other 3 13 not enough negative samples
IBD 4 13 not enough negative samples
IBD 2 13 not enough negative samples
Autoimmune: Other 3 13 not enough negative samples
IBD 4 13 not enough negative samples
IBD 0 14 not enough negative samples
IBD 1 14 not enough negative samples
IBD 2 14 not enough negative samples
Cancer: Other 3 14 not enough negative samples
Autoimmune: Other 4 14 not enough negative samples
IBD 0 14 not enough negative samples
IBD 1 14 not enough negative samples
IBD 2 14 not enough negative samples
Cancer: Other 3 14 not enough negative samples
Autoimmune: Other 4 14 not enough negative samples
IBD 0 14 not enough negative samples
IBD 1 14 not enough negative samples
IBD 2 14 not enough negative samples
Cancer: Other 3 14 not enough negative samples
Autoimmune: Other 4 14 not enough negative samples
IBD 0 14 not enough negative samples
IBD 1 14 not enough negative samples
IBD 2 14 not enough negative samples
Cancer: Other 3 14 not enough negative samples
Autoimmune: Other 4 14 not enough negative samples
IBD 0 15 not enough negative samples
IBD 2 15 not enough negative samples
HIV 4 15 not enough negative samples
IBD 4 15 not enough negative samples
IBD 0 15 not enough negative samples
IBD 2 15 not enough negative samples
HIV 4 15 not enough negative samples
IBD 4 15 not enough negative samples
IBD 0 15 not enough negative samples
IBD 2 15 not enough negative samples
HIV 4 15 not enough negative samples
IBD 4 15 not enough negative samples
IBD 0 15 not enough negative samples
IBD 2 15 not enough negative samples
HIV 4 15 not enough negative samples
IBD 4 15 not enough negative samples
IBD 0 16 not enough negative samples
Cancer: Other 1 16 not enough negative samples
Cancer: Other 2 16 not enough negative samples
IBD 2 16 not enough negative samples
IBD 0 16 not enough negative samples
Cancer: Other 1 16 not enough negative samples
Cancer: Other 2 16 not enough negative samples
IBD 2 16 not enough negative samples
IBD 0 16 not enough negative samples
Cancer: Other 1 16 not enough negative samples
Cancer: Other 2 16 not enough negative samples
IBD 2 16 not enough negative samples
IBD 0 16 not enough negative samples
Cancer: Other 1 16 not enough negative samples
Cancer: Other 2 16 not enough negative samples
IBD 2 16 not enough negative samples
Cancer: Other 0 17 not enough negative samples
IBD 1 17 not enough negative samples
Autoimmune: Other 2 17 not enough negative samples
HIV 2 17 not enough negative samples
IBD 3 17 not enough negative samples
IBD 4 17 not enough negative samples
Cancer: Other 0 17 not enough negative samples
IBD 1 17 not enough negative samples
Autoimmune: Other 2 17 not enough negative samples
HIV 2 17 not enough negative samples
IBD 3 17 not enough negative samples
IBD 4 17 not enough negative samples
Cancer: Other 0 17 not enough negative samples
IBD 1 17 not enough negative samples
Autoimmune: Other 2 17 not enough negative samples
HIV 2 17 not enough negative samples
IBD 3 17 not enough negative samples
IBD 4 17 not enough negative samples
Cancer: Other 0 17 not enough negative samples
IBD 1 17 not enough negative samples
Autoimmune: Other 2 17 not enough negative samples
HIV 2 17 not enough negative samples
IBD 3 17 not enough negative samples
IBD 4 17 not enough negative samples
IBD 0 18 not enough negative samples
Autoimmune: Other 2 18 not enough negative samples
Cancer: Other 3 18 not enough negative samples
IBD 3 18 not enough negative samples
Cancer: Other 4 18 not enough negative samples
IBD 4 18 not enough negative samples
IBD 0 18 not enough negative samples
Autoimmune: Other 2 18 not enough negative samples
Cancer: Other 3 18 not enough negative samples
IBD 3 18 not enough negative samples
Cancer: Other 4 18 not enough negative samples
IBD 4 18 not enough negative samples
IBD 0 18 not enough negative samples
Autoimmune: Other 2 18 not enough negative samples
Cancer: Other 3 18 not enough negative samples
IBD 3 18 not enough negative samples
Cancer: Other 4 18 not enough negative samples
IBD 4 18 not enough negative samples
IBD 0 18 not enough negative samples
Autoimmune: Other 2 18 not enough negative samples
Cancer: Other 3 18 not enough negative samples
IBD 3 18 not enough negative samples
Cancer: Other 4 18 not enough negative samples
IBD 4 18 not enough negative samples
Healthy Control 2 19 not enough negative samples
IBD 3 19 not enough negative samples
IBD 4 19 not enough negative samples
Healthy Control 2 19 not enough negative samples
IBD 3 19 not enough negative samples
IBD 4 19 not enough negative samples
Healthy Control 2 19 not enough negative samples
IBD 3 19 not enough negative samples
IBD 4 19 not enough negative samples
Healthy Control 2 19 not enough negative samples
IBD 3 19 not enough negative samples
IBD 4 19 not enough negative samples
Cancer: Other 1 20 not enough negative samples
IBD 2 20 not enough negative samples
IBD 3 20 not enough negative samples
HIV 4 20 not enough negative samples
IBD 4 20 not enough negative samples
Cancer: Other 1 20 not enough negative samples
IBD 2 20 not enough negative samples
IBD 3 20 not enough negative samples
HIV 4 20 not enough negative samples
IBD 4 20 not enough negative samples
Cancer: Other 1 20 not enough negative samples
IBD 2 20 not enough negative samples
IBD 3 20 not enough negative samples
HIV 4 20 not enough negative samples
IBD 4 20 not enough negative samples
Cancer: Other 1 20 not enough negative samples
IBD 2 20 not enough negative samples
IBD 3 20 not enough negative samples
HIV 4 20 not enough negative samples
IBD 4 20 not enough negative samples
IBD 0 21 not enough negative samples
Autoimmune: Other 2 21 not enough negative samples
IBD 2 21 not enough negative samples
Cancer: Other 4 21 not enough negative samples
IBD 0 21 not enough negative samples
Autoimmune: Other 2 21 not enough negative samples
IBD 2 21 not enough negative samples
Cancer: Other 4 21 not enough negative samples
IBD 0 21 not enough negative samples
Autoimmune: Other 2 21 not enough negative samples
IBD 2 21 not enough negative samples
Cancer: Other 4 21 not enough negative samples
IBD 0 21 not enough negative samples
Autoimmune: Other 2 21 not enough negative samples
IBD 2 21 not enough negative samples
Cancer: Other 4 21 not enough negative samples
IBD 0 22 not enough negative samples
IBD 2 22 not enough negative samples
Cancer: Other 3 22 not enough negative samples
HIV 4 22 not enough negative samples
IBD 4 22 not enough negative samples
IBD 0 22 not enough negative samples
IBD 2 22 not enough negative samples
Cancer: Other 3 22 not enough negative samples
HIV 4 22 not enough negative samples
IBD 4 22 not enough negative samples
IBD 0 22 not enough negative samples
IBD 2 22 not enough negative samples
Cancer: Other 3 22 not enough negative samples
HIV 4 22 not enough negative samples
IBD 4 22 not enough negative samples
IBD 0 22 not enough negative samples
IBD 2 22 not enough negative samples
Cancer: Other 3 22 not enough negative samples
HIV 4 22 not enough negative samples
IBD 4 22 not enough negative samples
IBD 1 23 not enough negative samples
Autoimmune: Other 3 23 not enough negative samples
IBD 3 23 not enough negative samples
IBD 4 23 not enough negative samples
IBD 1 23 not enough negative samples
Autoimmune: Other 3 23 not enough negative samples
IBD 3 23 not enough negative samples
IBD 4 23 not enough negative samples
IBD 1 23 not enough negative samples
Autoimmune: Other 3 23 not enough negative samples
IBD 3 23 not enough negative samples
IBD 4 23 not enough negative samples
IBD 1 23 not enough negative samples
Autoimmune: Other 3 23 not enough negative samples
IBD 3 23 not enough negative samples
IBD 4 23 not enough negative samples
Healthy Control 0 24 not enough negative samples
Autoimmune: Other 0 24 not enough negative samples
IBD 1 24 not enough negative samples
IBD 2 24 not enough negative samples
Cancer: Other 3 24 not enough negative samples
Healthy Control 0 24 not enough negative samples
Autoimmune: Other 0 24 not enough negative samples
IBD 1 24 not enough negative samples
IBD 2 24 not enough negative samples
Cancer: Other 3 24 not enough negative samples
Healthy Control 0 24 not enough negative samples
Autoimmune: Other 0 24 not enough negative samples
IBD 1 24 not enough negative samples
IBD 2 24 not enough negative samples
Cancer: Other 3 24 not enough negative samples
Healthy Control 0 24 not enough negative samples
Autoimmune: Other 0 24 not enough negative samples
IBD 1 24 not enough negative samples
IBD 2 24 not enough negative samples
Cancer: Other 3 24 not enough negative samples
Autoimmune: Other 0 25 not enough negative samples
Cancer: Other 1 25 not enough negative samples
IBD 1 25 not enough negative samples
IBD 2 25 not enough negative samples
IBD 3 25 not enough negative samples
Cancer: Other 4 25 not enough negative samples
IBD 4 25 not enough negative samples
Autoimmune: Other 0 25 not enough negative samples
Cancer: Other 1 25 not enough negative samples
IBD 1 25 not enough negative samples
IBD 2 25 not enough negative samples
IBD 3 25 not enough negative samples
Cancer: Other 4 25 not enough negative samples
IBD 4 25 not enough negative samples
Autoimmune: Other 0 25 not enough negative samples
Cancer: Other 1 25 not enough negative samples
IBD 1 25 not enough negative samples
IBD 2 25 not enough negative samples
IBD 3 25 not enough negative samples
Cancer: Other 4 25 not enough negative samples
IBD 4 25 not enough negative samples
Autoimmune: Other 0 25 not enough negative samples
Cancer: Other 1 25 not enough negative samples
IBD 1 25 not enough negative samples
IBD 2 25 not enough negative samples
IBD 3 25 not enough negative samples
Cancer: Other 4 25 not enough negative samples
IBD 4 25 not enough negative samples
IBD 0 26 not enough negative samples
IBD 1 26 not enough negative samples
IBD 2 26 not enough negative samples
IBD 0 26 not enough negative samples
IBD 1 26 not enough negative samples
IBD 2 26 not enough negative samples
IBD 0 26 not enough negative samples
IBD 1 26 not enough negative samples
IBD 2 26 not enough negative samples
IBD 0 26 not enough negative samples
IBD 1 26 not enough negative samples
IBD 2 26 not enough negative samples
Cancer: Other 2 27 not enough negative samples
IBD 2 27 not enough negative samples
Autoimmune: Other 3 27 not enough negative samples
IBD 3 27 not enough negative samples
IBD 4 27 not enough negative samples
Cancer: Other 2 27 not enough negative samples
IBD 2 27 not enough negative samples
Autoimmune: Other 3 27 not enough negative samples
IBD 3 27 not enough negative samples
IBD 4 27 not enough negative samples
Cancer: Other 2 27 not enough negative samples
IBD 2 27 not enough negative samples
Autoimmune: Other 3 27 not enough negative samples

In [21]:
columns = []
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Sensitivity at {t} Specificity')
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Specificity at {t} Sensitivity')
columns = [
    'Low Responders Accuracy',
    'High Responders Accuracy',
    'Harmonic Mean',
    'AUC'
] + columns



records = []
for k, v in metrics.items():
    seed, fold, cohort, clf, setting, usage = k.split(', ')
    records.append({
        'seed': int(seed),
        'fold': int(fold),
        'cohort': cohort,
        'setting': setting,
        'clf': clf,
        'usage': usage,
        **{name: val for name, val in zip(columns, v)}
    })

df = pd.DataFrame(records)

group_cols = ['cohort', 'setting', 'clf', 'usage']
metric_cols = columns

agg_df = df.groupby(group_cols)[metric_cols].agg(['mean', 'std']).reset_index()
agg_df.columns = ['_'.join(col).strip('_') for col in agg_df.columns.values]
agg_df

,cohort,setting,clf,usage,Low Responders Accuracy_mean,Low Responders Accuracy_std,High Responders Accuracy_mean,High Responders Accuracy_std,Harmonic Mean_mean,Harmonic Mean_std,...,Specificity at 0.75 Sensitivity_mean,Specificity at 0.75 Sensitivity_std,Specificity at 0.8 Sensitivity_mean,Specificity at 0.8 Sensitivity_std,Specificity at 0.85 Sensitivity_mean,Specificity at 0.85 Sensitivity_std,Specificity at 0.9 Sensitivity_mean,Specificity at 0.9 Sensitivity_std,Specificity at 0.95 Sensitivity_mean,Specificity at 0.95 Sensitivity_std
0,Autoimmune: Other,binary,mlp,Ab raw,0.386317,0.379861,0.729687,0.204286,0.357517,0.317924,...,0.109704,0.204062,0.101669,0.196490,0.029125,0.109504,0.001317,0.016812,0.000000,0.000000
1,Autoimmune: Other,binary,mlp,Demographic,0.311008,0.365390,0.751906,0.217444,0.285223,0.303827,...,0.100048,0.193493,0.092496,0.185471,0.028884,0.100462,0.001662,0.021515,0.000000,0.000000
2,Autoimmune: Other,no-cutoff,mlp,Ab raw,0.466713,0.372188,0.719466,0.209214,0.437781,0.307367,...,0.123794,0.223435,0.116716,0.218491,0.034895,0.124031,0.002751,0.040117,0.000000,0.000000
3,Autoimmune: Other,no-cutoff,mlp,Demographic,0.356045,0.369901,0.744859,0.227968,0.330795,0.311989,...,0.097986,0.197895,0.092955,0.194081,0.030263,0.115088,0.000000,0.000000,0.000000,0.000000
4,Cancer: Other,binary,mlp,Ab raw,0.323342,0.411533,0.791691,0.178714,0.301743,0.364772,...,0.037113,0.138142,0.037113,0.138142,0.002082,0.022808,0.000000,0.000000,0.000000,0.000000
5,Cancer: Other,binary,mlp,Demographic,0.357068,0.425639,0.809625,0.186666,0.323341,0.368651,...,0.041364,0.150688,0.039401,0.146251,0.003130,0.036435,0.000000,0.000000,0.000000,0.000000
6,Cancer: Other,no-cutoff,mlp,Ab raw,0.371771,0.421602,0.786413,0.191908,0.347035,0.371652,...,0.044533,0.156488,0.044533,0.156488,0.003544,0.048089,0.000000,0.000000,0.000000,0.000000
7,Cancer: Other,no-cutoff,mlp,Demographic,0.287260,0.405423,0.833301,0.177158,0.263397,0.356642,...,0.040852,0.156353,0.040852,0.156353,0.000698,0.013644,0.000000,0.000000,0.000000,0.000000
8,HIV,binary,mlp,Ab raw,0.539541,0.344925,0.662551,0.226619,0.478758,0.272045,...,0.179464,0.254999,0.160753,0.243773,0.070082,0.169214,0.005734,0.049876,0.000000,0.000000
9,HIV,binary,mlp,Demographic,0.552487,0.344009,0.679253,0.227981,0.493723,0.274490,...,0.173900,0.250223,0.154981,0.237868,0.070922,0.170478,0.008723,0.064134,0.000000,0.000000
10,HIV,no-cutoff,mlp,Ab raw,0.543417,0.352268,0.661028,0.227024,0.474003,0.270826,...,0.170074,0.249869,0.159620,0.245138,0.076601,0.179237,0.006711,0.052881,0.000000,0.000000
11,HIV,no-cutoff,mlp,Demographic,0.553260,0.346737,0.718986,0.224520,0.509621,0.275013,...,0.180456,0.255962,0.166957,0.248337,0.083649,0.182381,0.006992,0.049584,0.000000,0.000000
12,Healthy Control,binary,mlp,Ab raw,0.419328,0.319443,0.779111,0.156688,0.442737,0.280020,...,0.251932,0.264972,0.223484,0.257735,0.123885,0.208314,0.017011,0.071429,0.000000,0.000000
13,Healthy Control,binary,mlp,Demographic,0.291480,0.298320,0.861699,0.139912,0.335789,0.299816,...,0.267694,0.282285,0.238522,0.271893,0.140928,0.235069,0.023661,0.097811,0.000000,0.000000
14,Healthy Control,no-cutoff,mlp,Ab raw,0.463831,0.320089,0.768410,0.161689,0.481922,0.271501,...,0.249633,0.260271,0.229091,0.255945,0.136855,0.213876,0.021112,0.083988,0.000000,0.000000
15,Healthy Control,no-cutoff,mlp,Demographic,0.256343,0.275763,0.901594,0.094026,0.318446,0.298774,...,0.246145,0.268527,0.213200,0.251330,0.119382,0.201815,0.019448,0.081637,0.000000,0.000000
16,IBD,binary,mlp,Ab raw,0.597959,0.478994,0.746954,0.252140,0.467396,0.404187,...,0.006803,0.076638,0.006803,0.076638,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,IBD,binary,mlp,Demographic,0.517007,0.487369,0.813597,0.240579,0.418444,0.418481,...,0.008503,0.082380,0.008503,0.082380,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,IBD,no-cutoff,mlp,Ab raw,0.504762,0.474150,0.753583,0.266074,0.397146,0.391753,...,0.004626,0.055289,0.004626,0.055289,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,IBD,no-cutoff,mlp,Demographic,0.412925,0.476584,0.831924,0.244147,0.335241,0.409503,...,0.003537,0.044417,0.003537,0.044417,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,Multiple Myeloma,binary,mlp,Ab raw,0.802649,0.177155,0.359950,0.228702,0.430818,0.194556,...,0.344113,0.223177,0.267692,0.215878,0.209749,0.197056,0.129076,0.159209,0.040193,0.103628
21,Multiple Myeloma,binary,mlp,Demographic,0.838908,0.186006,0.323768,0.251321,0.382467,0.233584,...,0.347415,0.222087,0.287386,0.213707,0.233799,0.204907,0.149836,0.180554,0.041139,0.108379
22,Multiple Myeloma,no-cutoff,mlp,Ab raw,0.797842,0.193907,0.362696,0.234359,0.425410,0.208237,...,0.332331,0.216957,0.263673,0.208161,0.214814,0.199967,0.128996,0.174510,0.030878,0.091947
23,Multiple Myeloma,no-cutoff,mlp,Demographic,0.862832,0.176796,0.266623,0.249740,0.322444,0.258391,...,0.345911,0.216121,0.295076,0.209463,0.232773,0.199926,0.160062,0.183013,0.046113,0.120799
24,Transplant,binary,mlp,Ab raw,0.558913,0.258882,0.526017,0.252566,0.434196,0.162365,...,0.266901,0.182787,0.218421,0.184939,0.168295,0.174775,0.089951,0.139396,0.031442,0.084090
25,Transplant,binary,mlp,Demographic,0.688049,0.251452,0.370648,0.253010,0.372494,0.190558,...,0.236464,0.175235,0.189324,0.161004,0.142188,0.149375,0.090364,0.125499,0.037107,0.085025
26,Transplant,no-cutoff,mlp,Ab raw,0.558418,0.266437,0.508493,0.256049,0.417200,0.160058,...,0.241166,0.166027,0.196539,0.160998,0.143003,0.144584,0.073791,0.116004,0.029893,0.081988
27,Transplant,no-cutoff,mlp,Demographic,0.740387,0.231493,0.280010,0.240469,0.306139,0.209632,...,0.213604,0.173773,0.164667,0.155760,0.132723,0.146613,0.082662,0.127302,0.028392,0.079544

In [22]:
counts = {}
X6, y6 , pid6, emb_list6, real_size6, encoder6 = load_6(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)
    
X2, y2 , pid2, emb_list2, real_size2, encoder2 = load_2(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)


X_train = X6
y_train = y6
X_test = X2
y_test = y2
for cohort in COHORTS:     
    
    idx2 = X_test[:, 0] == cohort

    counts[f'{cohort},Test_N_Low'] = (y_test[idx2] == 0).astype(float).sum()
    counts[f'{cohort},Test_N_High'] = (y_test[idx2] == 1).astype(float).sum()
    counts[f'All,Train_N_Low'] = (y_train == 0).astype(float).sum()
    counts[f'All,Train_N_High'] = (y_train == 1).astype(float).sum()

counts

{'Autoimmune: Other,Test_N_Low': 12.0,
 'Autoimmune: Other,Test_N_High': 62.0,
 'All,Train_N_Low': 191.0,
 'All,Train_N_High': 882.0,
 'Cancer: Other,Test_N_Low': 6.0,
 'Cancer: Other,Test_N_High': 77.0,
 'HIV,Test_N_Low': 14.0,
 'HIV,Test_N_High': 62.0,
 'Healthy Control,Test_N_Low': 18.0,
 'Healthy Control,Test_N_High': 422.0,
 'IBD,Test_N_Low': 3.0,
 'IBD,Test_N_High': 28.0,
 'Multiple Myeloma,Test_N_Low': 42.0,
 'Multiple Myeloma,Test_N_High': 78.0,
 'Transplant,Test_N_Low': 50.0,
 'Transplant,Test_N_High': 56.0}

In [23]:
agg_df['Train_Timepoint'] = 'Post-B'
agg_df['Test_Timepoint'] = 'Pre-B'

agg_df['Test_Cohort'] = agg_df['cohort']
agg_df['Train_Cohort'] = 'All'



def update_usage(row, what):
    cohort = row['cohort']
    try:
        return counts[f'{cohort},{what}']
    except:
        return counts[f'All,{what}']

# Apply transformation
for what in ['Train_N_Low', 'Train_N_High', 'Test_N_High', 'Test_N_Low']:
    agg_df[what] = agg_df.apply(lambda z:update_usage(z, what=what), axis=1)
    
    
agg_df = agg_df.rename(columns={
    # 'cohort': 'Train_Cohort', 
    'clf': 'Classifier', 
    'AUC_mean': 'CV_AUC_Mean',
    'AUC_std': 'CV_AUC_SD',
    'Sensitivity at 0.8 Specificity_mean': 'CV_Sen_at_80_Spe_Mean',
    'Sensitivity at 0.8 Specificity_std': 'CV_Sen_at_80_Spe_SD',
    'Low Responders Accuracy_mean': 'CV_Acc_Low_Mean',
    'High Responders Accuracy_mean': 'CV_Acc_High_Mean',
    'Low Responders Accuracy_std': 'CV_Acc_Low_SD',
    'High Responders Accuracy_std': 'CV_Acc_High_SD',
})

def update_usage(row):
    # Start with base usage name
    usage = row['usage']
    setting = row['setting']
    
    
    # Case 1: if usage is "Ab raw"
    
    out = 'Ab_raw'
    
    
    # Case 2: if usage is "Demographic"
    if setting.strip().lower() == 'binary':
        out += '+ Ab_binary'
        
    if usage.strip().lower() == 'demographic':
        out += '+ demographic'
    
    # Case 3: modify further based on 'setting'
    
    if setting.strip().lower() == 'no-cutoff':
        # don't add anything
        pass
    
    return out

# Apply transformation
agg_df['Feature_Set'] = agg_df.apply(update_usage, axis=1)
agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier', 'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]

,Train_Timepoint,Train_Cohort,Train_N_Low,Train_N_High,Feature_Set,Test_Timepoint,Test_Cohort,Test_N_Low,Test_N_High,Classifier,CV_AUC_Mean,CV_AUC_SD,CV_Sen_at_80_Spe_Mean,CV_Sen_at_80_Spe_SD,CV_Acc_Low_Mean,CV_Acc_Low_SD,CV_Acc_High_Mean,CV_Acc_High_SD
0,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Pre-B,Autoimmune: Other,12.0,62.0,mlp,0.597751,0.218082,0.487688,0.352525,0.386317,0.379861,0.729687,0.204286
1,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Pre-B,Autoimmune: Other,12.0,62.0,mlp,0.550216,0.221650,0.416419,0.348955,0.311008,0.365390,0.751906,0.217444
2,Post-B,All,191.0,882.0,Ab_raw,Pre-B,Autoimmune: Other,12.0,62.0,mlp,0.613540,0.233752,0.500639,0.338951,0.466713,0.372188,0.719466,0.209214
3,Post-B,All,191.0,882.0,Ab_raw+ demographic,Pre-B,Autoimmune: Other,12.0,62.0,mlp,0.567604,0.240376,0.435039,0.356392,0.356045,0.369901,0.744859,0.227968
4,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Pre-B,Cancer: Other,6.0,77.0,mlp,0.606028,0.260843,0.482024,0.431794,0.323342,0.411533,0.791691,0.178714
5,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Pre-B,Cancer: Other,6.0,77.0,mlp,0.647525,0.252708,0.551963,0.430626,0.357068,0.425639,0.809625,0.186666
6,Post-B,All,191.0,882.0,Ab_raw,Pre-B,Cancer: Other,6.0,77.0,mlp,0.625946,0.264697,0.500698,0.431841,0.371771,0.421602,0.786413,0.191908
7,Post-B,All,191.0,882.0,Ab_raw+ demographic,Pre-B,Cancer: Other,6.0,77.0,mlp,0.646951,0.257885,0.532461,0.437920,0.287260,0.405423,0.833301,0.177158
8,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Pre-B,HIV,14.0,62.0,mlp,0.657387,0.206474,0.553105,0.320418,0.539541,0.344925,0.662551,0.226619
9,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Pre-B,HIV,14.0,62.0,mlp,0.667974,0.211387,0.588352,0.321922,0.552487,0.344009,0.679253,0.227981
10,Post-B,All,191.0,882.0,Ab_raw,Pre-B,HIV,14.0,62.0,mlp,0.662810,0.203496,0.555145,0.329011,0.543417,0.352268,0.661028,0.227024
11,Post-B,All,191.0,882.0,Ab_raw+ demographic,Pre-B,HIV,14.0,62.0,mlp,0.694309,0.201406,0.615413,0.314422,0.553260,0.346737,0.718986,0.224520
12,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Pre-B,Healthy Control,18.0,422.0,mlp,0.652387,0.165595,0.517009,0.272857,0.419328,0.319443,0.779111,0.156688
13,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Pre-B,Healthy Control,18.0,422.0,mlp,0.653873,0.170176,0.524940,0.273694,0.291480,0.298320,0.861699,0.139912
14,Post-B,All,191.0,882.0,Ab_raw,Pre-B,Healthy Control,18.0,422.0,mlp,0.665812,0.166763,0.518176,0.282396,0.463831,0.320089,0.768410,0.161689
15,Post-B,All,191.0,882.0,Ab_raw+ demographic,Pre-B,Healthy Control,18.0,422.0,mlp,0.654863,0.167881,0.534845,0.272589,0.256343,0.275763,0.901594,0.094026
16,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Pre-B,IBD,3.0,28.0,mlp,0.812886,0.240386,0.791156,0.394681,0.597959,0.478994,0.746954,0.252140
17,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Pre-B,IBD,3.0,28.0,mlp,0.817219,0.241907,0.802721,0.384516,0.517007,0.487369,0.813597,0.240579
18,Post-B,All,191.0,882.0,Ab_raw,Pre-B,IBD,3.0,28.0,mlp,0.723546,0.286662,0.663946,0.445829,0.504762,0.474150,0.753583,0.266074
19,Post-B,All,191.0,882.0,Ab_raw+ demographic,Pre-B,IBD,3.0,28.0,mlp,0.735222,0.292867,0.685034,0.439669,0.412925,0.476584,0.831924,0.244147
20,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Pre-B,Multiple Myeloma,42.0,78.0,mlp,0.642521,0.126542,0.449649,0.275966,0.802649,0.177155,0.359950,0.228702
21,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Pre-B,Multiple Myeloma,42.0,78.0,mlp,0.647683,0.123398,0.413590,0.279815,0.838908,0.186006,0.323768,0.251321
22,Post-B,All,191.0,882.0,Ab_raw,Pre-B,Multiple Myeloma,42.0,78.0,mlp,0.630158,0.131161,0.422640,0.274826,0.797842,0.193907,0.362696,0.234359
23,Post-B,All,191.0,882.0,Ab_raw+ demographic,Pre-B,Multiple Myeloma,42.0,78.0,mlp,0.626069,0.124257,0.379411,0.268574,0.862832,0.176796,0.266623,0.249740
24,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Pre-B,Transplant,50.0,56.0,mlp,0.567606,0.116393,0.373574,0.189374,0.558913,0.258882,0.526017,0.252566
25,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Pre-B,Transplant,50.0,56.0,mlp,0.560356,0.126579,0.358349,0.221634,0.688049,0.251452,0.370648,0.253010
26,Post-B,All,191.0,882.0,Ab_raw,Pre-B,Transplant,50.0,56.0,mlp,0.548094,0.113429,0.352348,0.188649,0.558418,0.266437,0.508493,0.256049
27,Post-B,All,191.0,882.0,Ab_raw+ demographic,Pre-B,Transplant,50.0,56.0,mlp,0.529739,0.121919,0.287841,0.215613,0.740387,0.231493,0.280010,0.240469

In [24]:
out = agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier',	'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]
out.to_csv(f'final_results_{DIM}d/model_performance_summary_v4_revised.csv')

#### Post to Pre All

In [25]:
metrics = {}

for k, v in results_6_excel.items():
    seed, task, setting, clf, coeffs, usage = re.split(r',\s*(?![^()]*\))', k)
    seed = int(seed)
    if setting == 'binary':
        cutoffs = GLOBAL_CUTOFFS
    else:
        cutoffs = None

    if 'raw' in usage:
        use_cat = False
    else:
        use_cat = True
    if use_cat:
            start_from = len(emb_list)
    else:
        start_from = 11
        
    
    X6, y6 , pid6, emb_list6, real_size6, encoder6 = load_6(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)
    
    X2, y2 , pid2, emb_list2, real_size2, encoder2 = load_2(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)
    
    size = real_size6 if use_cat else real_size6 - 1
    
     
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    
    
    for_stratify = y6
    for fold, (train_idx, test_idx) in enumerate(skf.split(X6, for_stratify), start=0):
        
        index = np.isin(pid2, pid6[test_idx])
        
        X_train = X6[train_idx]
        y_train = y6[train_idx]
        X_test = X2[index]
        y_test = y2[index]
        
        
        
        #################################################### Dataset
        
        X_train_tensor = torch.from_numpy(X_train[:, start_from:].astype(np.float32))
        y_train_tensor = torch.from_numpy(y_train).float()
        
        X_test_tensor = torch.from_numpy(X_test[:, start_from:].astype(np.float32))
        y_test_tensor = torch.from_numpy(y_test).float()
        
        # stratified split using sklearn
        train_idx, val_idx = train_test_split(
            np.arange(len(X_train_tensor)),
            test_size=0.2,
            stratify=y_train_tensor.numpy() ,
            random_state=seed
        )
        
        # create datasets
        train_dataset = TensorDataset(X_train_tensor[train_idx], y_train_tensor[train_idx])
        val_dataset   = TensorDataset(X_train_tensor[val_idx],  y_train_tensor[val_idx])
        
        # data loaders
        train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True, generator=torch.Generator().manual_seed(seed))
        val_loader   = DataLoader(val_dataset,   batch_size=len(val_dataset), shuffle=False)
        test_loader = DataLoader(TensorDataset(X_test_tensor, y_test_tensor),
                                 batch_size=len(X_test_tensor), shuffle=False)
        
        m = BottleneckMLP(emb_list, size, start_from, 8, (128, 64, DIM), p=0.2, use_cat=use_cat, binary=True).to(device)
        
        m.load_state_dict(v[0][fold])
        
        
        
        for x_batch, y_batch in test_loader:
            pass
        
        if clf == 'mlp':
            with torch.no_grad():
                m.eval()
                logits, two_d = m(x_batch.to(device))
        else:
            with torch.no_grad():
                x_for_clf = []
                y_for_clf = []
                for x_batch_train, y_batch_train in train_loader:
                    with torch.no_grad():
                        m.eval()
                        _, two_d = m(x_batch_train.to(device))
                    x_for_clf.extend(two_d)
                    y_for_clf.extend(y_batch_train)
            x_for_clf = torch.stack(x_for_clf).cpu().numpy()
            y_for_clf = torch.stack(y_for_clf).cpu().numpy()
            if clf == 'svm':
                one = (y_for_clf == 1).astype(float).sum()
                zero = (y_for_clf == 0).astype(float).sum()
                w = (one/zero)
                delta = 1
    
                classifier = SVC(kernel="rbf", class_weight={0: w, 1: 1}, probability=True)
                classifier.fit(x_for_clf, y_for_clf)
                with torch.no_grad():
                    m.eval()
                    x_in = m(x_batch.to(device))[-1].cpu().numpy()
                logits = classifier.decision_function(x_in)
            elif clf == 'nc':
                classifier = NearestCentroid(metric="euclidean")
                classifier.fit(x_for_clf, y_for_clf)
                with torch.no_grad():
                    m.eval()
                    x_in = m(x_batch.to(device))[-1].cpu().numpy()
                logits = classifier.predict(x_in)

        if 1:
            if clf == 'mlp':
                y_pred = (logits.reshape(-1) > 0.5).int().cpu()
            elif clf == 'svm':
                y_pred = torch.from_numpy(logits >= delta).int()
            elif clf == 'nc':
                
                y_pred = torch.from_numpy(logits).int()
            a_test = (y_pred[y_batch==0] == y_batch[y_batch==0]).float().mean().item() + 1e-20
            b_test = (y_pred[y_batch==1] == y_batch[y_batch==1]).float().mean().item() + 1e-20
            c_test = 2 / ((1/a_test) + 1/b_test)
            if clf == 'svm':
                logits = torch.sigmoid(torch.from_numpy(logits))
            elif clf == 'nc':
                D = pairwise_distances(x_in, classifier.centroids_, metric=classifier.metric)
                pos_idx = np.where(classifier.classes_ == 1)[0][0]
                logits = torch.from_numpy(-D[:, pos_idx])
                # logits = torch.sigmoid(torch.from_numpy(logits))

            try:
                auc_test = roc_auc_score(y_batch.cpu().numpy(), logits.cpu().numpy())
            except:
                auc_test = None
            sen_test = []
            spec_test = []
            for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
                sen_, spec_ = at_95(logits.cpu().numpy(), y_batch, t=t)
                sen_test.append(sen_)
                spec_test.append(spec_)
                
        
        metrics[f'{seed}, {fold}, {clf}, {setting}, {usage}'] = ([a_test, b_test, c_test, auc_test, *spec_test, *sen_test])

In [26]:
columns = []
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Sensitivity at {t} Specificity')
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Specificity at {t} Sensitivity')
columns = [
    'Low Responders Accuracy',
    'High Responders Accuracy',
    'Harmonic Mean',
    'AUC'
] + columns


records = []
for k, v in metrics.items():
    seed, fold, clf, setting, usage = k.split(', ')
    records.append({
        'seed': int(seed),
        'fold': int(fold),
        'cohort': 'All',
        'setting': setting,
        'clf': clf,
        'usage': usage,
        **{name: val for name, val in zip(columns, v)}
    })

df = pd.DataFrame(records)

group_cols = ['cohort', 'setting', 'clf', 'usage']
metric_cols = columns

agg_df = df.groupby(group_cols)[metric_cols].agg(['mean', 'std']).reset_index()
agg_df.columns = ['_'.join(col).strip('_') for col in agg_df.columns.values]
agg_df

,cohort,setting,clf,usage,Low Responders Accuracy_mean,Low Responders Accuracy_std,High Responders Accuracy_mean,High Responders Accuracy_std,Harmonic Mean_mean,Harmonic Mean_std,...,Specificity at 0.75 Sensitivity_mean,Specificity at 0.75 Sensitivity_std,Specificity at 0.8 Sensitivity_mean,Specificity at 0.8 Sensitivity_std,Specificity at 0.85 Sensitivity_mean,Specificity at 0.85 Sensitivity_std,Specificity at 0.9 Sensitivity_mean,Specificity at 0.9 Sensitivity_std,Specificity at 0.95 Sensitivity_mean,Specificity at 0.95 Sensitivity_std
0,All,binary,mlp,Ab raw,0.582719,0.197860,0.705963,0.165279,0.587417,0.108008,...,0.539162,0.115964,0.471341,0.134728,0.366153,0.164204,0.236205,0.160525,0.103065,0.110215
1,All,binary,mlp,Demographic,0.618565,0.198526,0.742243,0.156936,0.628128,0.114198,...,0.627804,0.110048,0.562766,0.124000,0.466307,0.162791,0.336744,0.181046,0.154045,0.166893
2,All,no-cutoff,mlp,Ab raw,0.595037,0.197053,0.696944,0.171467,0.590454,0.102951,...,0.527906,0.114666,0.465471,0.127417,0.364794,0.151150,0.234733,0.154478,0.114021,0.116473
3,All,no-cutoff,mlp,Demographic,0.635867,0.184781,0.755458,0.130054,0.655292,0.090892,...,0.657363,0.111585,0.586529,0.129369,0.503191,0.152061,0.354351,0.193987,0.160418,0.155623

In [27]:
counts = {}
X6, y6 , pid6, emb_list6, real_size6, encoder6 = load_6(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)
    
X2, y2 , pid2, emb_list2, real_size2, encoder2 = load_2(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)


X_train = X6
y_train = y6
X_test = X2
y_test = y2


counts[f'Test_N_Low'] = (y_test == 0).astype(float).sum()
counts[f'Test_N_High'] = (y_test == 1).astype(float).sum()
counts[f'Train_N_Low'] = (y_train == 0).astype(float).sum()
counts[f'Train_N_High'] = (y_train == 1).astype(float).sum()

counts

{'Test_N_Low': 145.0,
 'Test_N_High': 785.0,
 'Train_N_Low': 191.0,
 'Train_N_High': 882.0}

In [28]:
agg_df['Train_Timepoint'] = 'Post-B'
agg_df['Test_Timepoint'] = 'Pre-B'

agg_df['Test_Cohort'] = agg_df['cohort']
agg_df['Train_Cohort'] = 'All'



def update_usage(row, what):
    # cohort = row['cohort']
    return counts[f'{what}']

# Apply transformation
for what in ['Train_N_Low', 'Train_N_High', 'Test_N_High', 'Test_N_Low']:
    agg_df[what] = agg_df.apply(lambda z:update_usage(z, what=what), axis=1)
    
    
agg_df = agg_df.rename(columns={
    # 'cohort': 'Train_Cohort', 
    'clf': 'Classifier', 
    'AUC_mean': 'CV_AUC_Mean',
    'AUC_std': 'CV_AUC_SD',
    'Sensitivity at 0.8 Specificity_mean': 'CV_Sen_at_80_Spe_Mean',
    'Sensitivity at 0.8 Specificity_std': 'CV_Sen_at_80_Spe_SD',
    'Low Responders Accuracy_mean': 'CV_Acc_Low_Mean',
    'High Responders Accuracy_mean': 'CV_Acc_High_Mean',
    'Low Responders Accuracy_std': 'CV_Acc_Low_SD',
    'High Responders Accuracy_std': 'CV_Acc_High_SD',
})

def update_usage(row):
    # Start with base usage name
    usage = row['usage']
    setting = row['setting']
    
    
    # Case 1: if usage is "Ab raw"
    
    out = 'Ab_raw'
    
    
    # Case 2: if usage is "Demographic"
    if setting.strip().lower() == 'binary':
        out += '+ Ab_binary'
        
    if usage.strip().lower() == 'demographic':
        out += '+ demographic'
    
    # Case 3: modify further based on 'setting'
    
    if setting.strip().lower() == 'no-cutoff':
        # don't add anything
        pass
    
    return out

# Apply transformation
agg_df['Feature_Set'] = agg_df.apply(update_usage, axis=1)
agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier', 'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]

,Train_Timepoint,Train_Cohort,Train_N_Low,Train_N_High,Feature_Set,Test_Timepoint,Test_Cohort,Test_N_Low,Test_N_High,Classifier,CV_AUC_Mean,CV_AUC_SD,CV_Sen_at_80_Spe_Mean,CV_Sen_at_80_Spe_SD,CV_Acc_Low_Mean,CV_Acc_Low_SD,CV_Acc_High_Mean,CV_Acc_High_SD
0,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary,Pre-B,All,145.0,785.0,mlp,0.713089,0.052082,0.523454,0.103103,0.582719,0.197860,0.705963,0.165279
1,Post-B,All,191.0,882.0,Ab_raw+ Ab_binary+ demographic,Pre-B,All,145.0,785.0,mlp,0.760354,0.048478,0.614695,0.097147,0.618565,0.198526,0.742243,0.156936
2,Post-B,All,191.0,882.0,Ab_raw,Pre-B,All,145.0,785.0,mlp,0.710532,0.055899,0.521351,0.104603,0.595037,0.197053,0.696944,0.171467
3,Post-B,All,191.0,882.0,Ab_raw+ demographic,Pre-B,All,145.0,785.0,mlp,0.772645,0.047278,0.641070,0.098280,0.635867,0.184781,0.755458,0.130054

In [29]:
out = agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier',	'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]
out.to_csv(f'final_results_{DIM}d/model_performance_summary_v5_revised.csv')

#### Post to Pre cohort by cohort

In [30]:
counts = {}
X6, y6 , pid6, emb_list6, real_size6, encoder6 = load_6(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)
    
X2, y2 , pid2, emb_list2, real_size2, encoder2 = load_2(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)


X_train = X6
y_train = y6
X_test = X2
y_test = y2

for cohort in COHORTS:     
    
    
    # idx = X[:, 0] == 'Healthy Control'
    idx1 = X_train[:, 0] == cohort
    idx2 = X_test[:, 0] == cohort

    counts[f'{cohort},Test_N_Low'] = (y_test[idx2] == 0).astype(float).sum()
    counts[f'{cohort},Test_N_High'] = (y_test[idx2] == 1).astype(float).sum()
    counts[f'{cohort},Train_N_Low'] = (y_train[idx1] == 0).astype(float).sum()
    counts[f'{cohort},Train_N_High'] = (y_train[idx1] == 1).astype(float).sum()

counts

{'Autoimmune: Other,Test_N_Low': 12.0,
 'Autoimmune: Other,Test_N_High': 62.0,
 'Autoimmune: Other,Train_N_Low': 13.0,
 'Autoimmune: Other,Train_N_High': 67.0,
 'Cancer: Other,Test_N_Low': 6.0,
 'Cancer: Other,Test_N_High': 77.0,
 'Cancer: Other,Train_N_Low': 8.0,
 'Cancer: Other,Train_N_High': 95.0,
 'HIV,Test_N_Low': 14.0,
 'HIV,Test_N_High': 62.0,
 'HIV,Train_N_Low': 14.0,
 'HIV,Train_N_High': 68.0,
 'Healthy Control,Test_N_Low': 18.0,
 'Healthy Control,Test_N_High': 422.0,
 'Healthy Control,Train_N_Low': 21.0,
 'Healthy Control,Train_N_High': 462.0,
 'IBD,Test_N_Low': 3.0,
 'IBD,Test_N_High': 28.0,
 'IBD,Train_N_Low': 4.0,
 'IBD,Train_N_High': 33.0,
 'Multiple Myeloma,Test_N_Low': 42.0,
 'Multiple Myeloma,Test_N_High': 78.0,
 'Multiple Myeloma,Train_N_Low': 60.0,
 'Multiple Myeloma,Train_N_High': 90.0,
 'Transplant,Test_N_Low': 50.0,
 'Transplant,Test_N_High': 56.0,
 'Transplant,Train_N_Low': 71.0,
 'Transplant,Train_N_High': 67.0}

In [31]:
metrics = {}

for k, v in results_8_excel.items():
    
    seed, cohort, task, setting, clf, coeffs, usage = re.split(r',\s*(?![^()]*\))', k)
    
    seed = int(seed)
    if setting == 'binary':
        cutoffs = GLOBAL_CUTOFFS
    else:
        cutoffs = None

    if 'raw' in usage:
        use_cat = False
    else:
        use_cat = True
    if use_cat:
            start_from = len(emb_list)
    else:
        start_from = 11
        
    
    X6, y6 , pid6, emb_list6, real_size6, encoder6 = load_6(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)
    
    X2, y2 , pid2, emb_list2, real_size2, encoder2 = load_2(binary=True, cutoffs=cutoffs, include_pid=True, include_all_vaccines=INCLUDE_OTHERS)
    
    idx = X6[:, 0] == cohort
    X6 = X6[idx]
    y6 = y6[idx]
    pid6 = pid6[idx]

    idx = X2[:, 0] == cohort
    X2 = X2[idx]
    y2 = y2[idx]
    pid2 = pid2[idx]
    
    size = real_size6 if use_cat else real_size6 - 1
         
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    
    
    for_stratify = y6
    for fold, (train_idx, test_idx) in enumerate(skf.split(X6, for_stratify), start=0):
        
        index = np.isin(pid2, pid6[test_idx])
        
        X_train = X6[train_idx]
        y_train = y6[train_idx]
        X_test = X2[index]
        y_test = y2[index]

        if (y_test == 0).sum() < 1:
            print('not enough samples for', cohort, fold, seed)
            continue
        
        
        #################################################### Dataset
        
        X_train_tensor = torch.from_numpy(X_train[:, start_from:].astype(np.float32))
        y_train_tensor = torch.from_numpy(y_train).float()
        
        X_test_tensor = torch.from_numpy(X_test[:, start_from:].astype(np.float32))
        y_test_tensor = torch.from_numpy(y_test).float()
        
        
        # stratified split using sklearn
        train_idx, val_idx = train_test_split(
            np.arange(len(X_train_tensor)),
            test_size=0.2,
            stratify=y_train_tensor.numpy() ,
            random_state=seed
        )
        
        # create datasets
        train_dataset = TensorDataset(X_train_tensor[train_idx], y_train_tensor[train_idx])
        val_dataset   = TensorDataset(X_train_tensor[val_idx],  y_train_tensor[val_idx])
        
        # data loaders
        train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True, generator=torch.Generator().manual_seed(seed))
        val_loader   = DataLoader(val_dataset,   batch_size=len(val_dataset), shuffle=False)
        test_loader = DataLoader(TensorDataset(X_test_tensor, y_test_tensor),
                                 batch_size=len(X_test_tensor), shuffle=False)
        
        m = BottleneckMLP(emb_list, size, start_from, 8, (128, 64, DIM), p=0.2, use_cat=use_cat, binary=True).to(device)
        
        m.load_state_dict(v[0][fold])
        
        
        # for cohort in en.keys():
        for x_batch, y_batch in test_loader:
            pass
        
        if clf == 'mlp':
            with torch.no_grad():
                m.eval()
                logits, two_d = m(x_batch.to(device))
        else:
            with torch.no_grad():
                x_for_clf = []
                y_for_clf = []
                for x_batch_train, y_batch_train in train_loader:
                    with torch.no_grad():
                        m.eval()
                        _, two_d = m(x_batch_train.to(device))
                    x_for_clf.extend(two_d)
                    y_for_clf.extend(y_batch_train)
            x_for_clf = torch.stack(x_for_clf).cpu().numpy()
            y_for_clf = torch.stack(y_for_clf).cpu().numpy()
            if clf == 'svm':
                one = (y_for_clf == 1).astype(float).sum()
                zero = (y_for_clf == 0).astype(float).sum()
                w = (one/zero)
                delta = 1
    
                classifier = SVC(kernel="rbf", class_weight={0: w, 1: 1}, probability=True)
                classifier.fit(x_for_clf, y_for_clf)
                with torch.no_grad():
                    m.eval()
                    x_in = m(x_batch.to(device))[-1].cpu().numpy()
                logits = classifier.decision_function(x_in)
            elif clf == 'nc':
                classifier = NearestCentroid(metric="euclidean")
                classifier.fit(x_for_clf, y_for_clf)
                with torch.no_grad():
                    m.eval()
                    x_in = m(x_batch.to(device))[-1].cpu().numpy()
                logits = classifier.predict(x_in)

        if 1:
            if clf == 'mlp':
                y_pred = (logits.reshape(-1) > 0.5).int().cpu()
            elif clf == 'svm':
                y_pred = torch.from_numpy(logits >= delta).int()
            elif clf == 'nc':
                
                y_pred = torch.from_numpy(logits).int()
            a_test = (y_pred[y_batch==0] == y_batch[y_batch==0]).float().mean().item() + 1e-20
            b_test = (y_pred[y_batch==1] == y_batch[y_batch==1]).float().mean().item() + 1e-20
            c_test = 2 / ((1/a_test) + 1/b_test)
            if clf == 'svm':
                logits = torch.sigmoid(torch.from_numpy(logits))
            elif clf == 'nc':
                D = pairwise_distances(x_in, classifier.centroids_, metric=classifier.metric)
                pos_idx = np.where(classifier.classes_ == 1)[0][0]
                logits = torch.from_numpy(-D[:, pos_idx])
                # logits = torch.sigmoid(torch.from_numpy(logits))

            try:
                auc_test = roc_auc_score(y_batch.cpu().numpy(), logits.cpu().numpy())
            except:
                auc_test = None
            sen_test = []
            spec_test = []
            for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
                sen_, spec_ = at_95(logits.cpu().numpy(), y_batch, t=t)
                sen_test.append(sen_)
                spec_test.append(spec_)
                
        
        metrics[f'{seed}, {cohort}, {fold}, {clf}, {setting}, {usage}'] = ([a_test, b_test, c_test, auc_test, *spec_test, *sen_test])

not enough samples for Cancer: Other 3 0
not enough samples for Cancer: Other 3 0
not enough samples for Cancer: Other 3 0
not enough samples for Cancer: Other 3 0
not enough samples for Cancer: Other 4 1
not enough samples for Cancer: Other 4 1
not enough samples for Cancer: Other 4 1
not enough samples for Cancer: Other 4 1
not enough samples for Cancer: Other 3 2
not enough samples for Cancer: Other 3 2
not enough samples for Cancer: Other 3 2
not enough samples for Cancer: Other 3 2
not enough samples for Cancer: Other 0 4
not enough samples for Cancer: Other 0 4
not enough samples for Cancer: Other 0 4
not enough samples for Cancer: Other 0 4
not enough samples for Cancer: Other 3 6
not enough samples for Cancer: Other 3 6
not enough samples for Cancer: Other 3 6
not enough samples for Cancer: Other 3 6
not enough samples for Cancer: Other 4 7
not enough samples for Cancer: Other 4 7
not enough samples for Cancer: Other 4 7
not enough samples for Cancer: Other 4 7
not enough samples for Cancer: Other 3 10
not enough samples for Cancer: Other 3 10
not enough samples for Cancer: Other 3 10
not enough samples for Cancer: Other 3 10
not enough samples for Cancer: Other 1 11
not enough samples for Cancer: Other 1 11
not enough samples for Cancer: Other 1 11
not enough samples for Cancer: Other 1 11
not enough samples for Cancer: Other 4 12
not enough samples for Cancer: Other 4 12
not enough samples for Cancer: Other 4 12
not enough samples for Cancer: Other 4 12
not enough samples for Cancer: Other 3 13
not enough samples for Cancer: Other 4 13
not enough samples for Cancer: Other 3 13
not enough samples for Cancer: Other 4 13
not enough samples for Cancer: Other 3 13
not enough samples for Cancer: Other 4 13
not enough samples for Cancer: Other 3 13
not enough samples for Cancer: Other 4 13
not enough samples for Cancer: Other 3 15
not enough samples for Cancer: Other 3 15
not enough samples for Cancer: Other 3 15
not enough samples for Cancer: Other 3 15
not enough samples for Cancer: Other 1 16
not enough samples for Cancer: Other 1 16
not enough samples for Cancer: Other 1 16
not enough samples for Cancer: Other 1 16
not enough samples for Cancer: Other 3 17
not enough samples for Cancer: Other 3 17
not enough samples for Cancer: Other 3 17
not enough samples for Cancer: Other 3 17
not enough samples for Cancer: Other 4 18
not enough samples for Cancer: Other 4 18
not enough samples for Cancer: Other 4 18
not enough samples for Cancer: Other 4 18
not enough samples for Cancer: Other 3 19
not enough samples for Cancer: Other 3 19
not enough samples for Cancer: Other 3 19
not enough samples for Cancer: Other 3 19
not enough samples for Cancer: Other 4 22
not enough samples for Cancer: Other 4 22
not enough samples for Cancer: Other 4 22
not enough samples for Cancer: Other 4 22
not enough samples for Cancer: Other 4 23
not enough samples for Cancer: Other 4 23
not enough samples for Cancer: Other 4 23
not enough samples for Cancer: Other 4 23
not enough samples for Cancer: Other 4 25
not enough samples for Cancer: Other 4 25
not enough samples for Cancer: Other 4 25
not enough samples for Cancer: Other 4 25
not enough samples for Cancer: Other 4 26
not enough samples for Cancer: Other 4 26
not enough samples for Cancer: Other 4 26
not enough samples for Cancer: Other 4 26
not enough samples for Cancer: Other 3 27
not enough samples for Cancer: Other 3 27
not enough samples for Cancer: Other 3 27
not enough samples for Cancer: Other 3 27
not enough samples for Cancer: Other 3 30
not enough samples for Cancer: Other 3 30
not enough samples for Cancer: Other 3 30
not enough samples for Cancer: Other 3 30
not enough samples for Cancer: Other 2 31
not enough samples for Cancer: Other 2 31
not enough samples for Cancer: Other 2 31
not enough samples for Cancer: Other 2 31
not enough samples for Cancer: Other 4 32
not enough samples for Cancer: Other 4 32
not enough samples for Cancer: Other 4 32
not enough samples for Cancer: Other 4 32
not enough samples for Cancer: Other 1 33
not enough samples for Cancer: Other 1 33
not enough samples for Cancer: Other 1 33
not enough samples for Cancer: Other 1 33
not enough samples for Cancer: Other 3 34
not enough samples for Cancer: Other 3 34
not enough samples for Cancer: Other 3 34
not enough samples for Cancer: Other 3 34
not enough samples for Cancer: Other 3 37
not enough samples for Cancer: Other 3 37
not enough samples for Cancer: Other 3 37
not enough samples for Cancer: Other 3 37
not enough samples for Cancer: Other 1 38
not enough samples for Cancer: Other 1 38
not enough samples for Cancer: Other 1 38
not enough samples for Cancer: Other 1 38
not enough samples for Cancer: Other 4 39
not enough samples for Cancer: Other 4 39
not enough samples for Cancer: Other 4 39
not enough samples for Cancer: Other 4 39
not enough samples for Cancer: Other 0 44
not enough samples for Cancer: Other 0 44
not enough samples for Cancer: Other 0 44
not enough samples for Cancer: Other 0 44
not enough samples for Cancer: Other 3 46
not enough samples for Cancer: Other 3 46
not enough samples for Cancer: Other 3 46
not enough samples for Cancer: Other 3 46
not enough samples for Cancer: Other 4 47
not enough samples for Cancer: Other 4 47
not enough samples for Cancer: Other 4 47
not enough samples for Cancer: Other 4 47
not enough samples for Cancer: Other 3 51
not enough samples for Cancer: Other 4 51
not enough samples for Cancer: Other 3 51
not enough samples for Cancer: Other 4 51
not enough samples for Cancer: Other 3 51
not enough samples for Cancer: Other 4 51
not enough samples for Cancer: Other 3 51
not enough samples for Cancer: Other 4 51
not enough samples for Cancer: Other 3 52
not enough samples for Cancer: Other 3 52
not enough samples for Cancer: Other 3 52
not enough samples for Cancer: Other 3 52
not enough samples for Cancer: Other 0 55
not enough samples for Cancer: Other 0 55
not enough samples for Cancer: Other 0 55
not enough samples for Cancer: Other 0 55
not enough samples for Cancer: Other 0 56
not enough samples for Cancer: Other 0 56
not enough samples for Cancer: Other 0 56
not enough samples for Cancer: Other 0 56
not enough samples for Cancer: Other 4 58
not enough samples for Cancer: Other 4 58
not enough samples for Cancer: Other 4 58
not enough samples for Cancer: Other 4 58
not enough samples for Cancer: Other 3 59
not enough samples for Cancer: Other 3 59
not enough samples for Cancer: Other 3 59
not enough samples for Cancer: Other 3 59
not enough samples for Cancer: Other 1 60
not enough samples for Cancer: Other 1 60
not enough samples for Cancer: Other 1 60
not enough samples for Cancer: Other 1 60
not enough samples for Cancer: Other 4 61
not enough samples for Cancer: Other 4 61
not enough samples for Cancer: Other 4 61
not enough samples for Cancer: Other 4 61
not enough samples for Cancer: Other 3 63
not enough samples for Cancer: Other 3 63
not enough samples for Cancer: Other 3 63
not enough samples for Cancer: Other 3 63
not enough samples for Cancer: Other 3 69
not enough samples for Cancer: Other 3 69
not enough samples for Cancer: Other 3 69
not enough samples for Cancer: Other 3 69
not enough samples for Cancer: Other 3 70
not enough samples for Cancer: Other 3 70
not enough samples for Cancer: Other 3 70
not enough samples for Cancer: Other 3 70
not enough samples for Cancer: Other 4 71
not enough samples for Cancer: Other 4 71
not enough samples for Cancer: Other 4 71
not enough samples for Cancer: Other 4 71
not enough samples for Cancer: Other 3 75
not enough samples for Cancer: Other 4 75
not enough samples for Cancer: Other 3 75
not enough samples for Cancer: Other 4 75
not enough samples for Cancer: Other 3 75
not enough samples for Cancer: Other 4 75
not enough samples for Cancer: Other 3 75
not enough samples for Cancer: Other 4 75
not enough samples for Cancer: Other 4 80
not enough samples for Cancer: Other 4 80
not enough samples for Cancer: Other 4 80
not enough samples for Cancer: Other 4 80
not enough samples for Cancer: Other 1 84
not enough samples for Cancer: Other 1 84
not enough samples for Cancer: Other 1 84
not enough samples for Cancer: Other 1 84
not enough samples for Cancer: Other 0 88
not enough samples for Cancer: Other 0 88
not enough samples for Cancer: Other 0 88
not enough samples for Cancer: Other 0 88
not enough samples for Cancer: Other 3 89
not enough samples for Cancer: Other 3 89
not enough samples for Cancer: Other 3 89
not enough samples for Cancer: Other 3 89
not enough samples for Cancer: Other 3 90
not enough samples for Cancer: Other 3 90
not enough samples for Cancer: Other 3 90
not enough samples for Cancer: Other 3 90
not enough samples for Cancer: Other 4 91
not enough samples for Cancer: Other 4 91
not enough samples for Cancer: Other 4 91
not enough samples for Cancer: Other 4 91
not enough samples for Cancer: Other 2 93
not enough samples for Cancer: Other 2 93
not enough samples for Cancer: Other 2 93
not enough samples for Cancer: Other 2 93
not enough samples for Cancer: Other 4 95
not enough samples for Cancer: Other 4 95
not enough samples for Cancer: Other 4 95
not enough samples for Cancer: Other 4 95
not enough samples for Cancer: Other 4 96
not enough samples for Cancer: Other 4 96
not enough samples for Cancer: Other 4 96
not enough samples for Cancer: Other 4 96
not enough samples for Cancer: Other 4 98
not enough samples for Cancer: Other 4 98
not enough samples for Cancer: Other 4 98
not enough samples for Cancer: Other 4 98

In [32]:
columns = []
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Sensitivity at {t} Specificity')
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Specificity at {t} Sensitivity')
columns = [
    'Low Responders Accuracy',
    'High Responders Accuracy',
    'Harmonic Mean',
    'AUC'
] + columns
for k, v in results_6_excel.items():
    seed, _, setting, clf, __, usage = re.split(r',\s*(?![^()]*\))', k)


records = []
for k, v in metrics.items():
    
    seed,  cohort, fold, clf, setting, usage = k.split(', ')
    
    records.append({
        'seed': int(seed),
        'fold': int(fold),
        'cohort': cohort,
        
        'setting': setting,
        'clf': clf,
        
        'usage': usage,
        **{name: val for name, val in zip(columns, v)}
    })

df = pd.DataFrame(records)

group_cols = ['cohort', 'setting', 'clf', 'usage']
metric_cols = columns

agg_df = df.groupby(group_cols)[metric_cols].agg(['mean', 'std']).reset_index()
agg_df.columns = ['_'.join(col).strip('_') for col in agg_df.columns.values]
agg_df

,cohort,setting,clf,usage,Low Responders Accuracy_mean,Low Responders Accuracy_std,High Responders Accuracy_mean,High Responders Accuracy_std,Harmonic Mean_mean,Harmonic Mean_std,...,Specificity at 0.75 Sensitivity_mean,Specificity at 0.75 Sensitivity_std,Specificity at 0.8 Sensitivity_mean,Specificity at 0.8 Sensitivity_std,Specificity at 0.85 Sensitivity_mean,Specificity at 0.85 Sensitivity_std,Specificity at 0.9 Sensitivity_mean,Specificity at 0.9 Sensitivity_std,Specificity at 0.95 Sensitivity_mean,Specificity at 0.95 Sensitivity_std
0,Autoimmune: Other,binary,mlp,Ab raw,0.527333,0.460929,0.477661,0.432361,0.118134,0.211131,...,0.086772,0.181036,0.086772,0.181036,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Autoimmune: Other,binary,mlp,Demographic,0.431667,0.452544,0.567488,0.433237,0.112229,0.206662,...,0.078542,0.172493,0.078542,0.172493,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Autoimmune: Other,no-cutoff,mlp,Ab raw,0.540667,0.452499,0.467968,0.421006,0.143560,0.231164,...,0.087734,0.175766,0.087734,0.175766,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,Autoimmune: Other,no-cutoff,mlp,Demographic,0.455000,0.458264,0.569083,0.431170,0.127178,0.213410,...,0.085037,0.183152,0.085037,0.183152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Cancer: Other,binary,mlp,Ab raw,0.488713,0.493037,0.507319,0.450962,0.075749,0.189781,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,Cancer: Other,binary,mlp,Demographic,0.445824,0.487861,0.567615,0.432740,0.100553,0.224360,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,Cancer: Other,no-cutoff,mlp,Ab raw,0.490971,0.486152,0.501807,0.437148,0.089425,0.195061,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,Cancer: Other,no-cutoff,mlp,Demographic,0.435666,0.486042,0.565775,0.435092,0.097490,0.200265,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,HIV,binary,mlp,Ab raw,0.530667,0.429710,0.528387,0.415201,0.193050,0.250011,...,0.194965,0.245817,0.194965,0.245817,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,HIV,binary,mlp,Demographic,0.458000,0.429009,0.607487,0.394092,0.205297,0.268995,...,0.201532,0.262442,0.201532,0.262442,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,HIV,no-cutoff,mlp,Ab raw,0.568667,0.409142,0.530758,0.391694,0.259644,0.277162,...,0.202796,0.256671,0.202796,0.256671,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,HIV,no-cutoff,mlp,Demographic,0.460333,0.426825,0.619157,0.392899,0.217249,0.261234,...,0.206424,0.251919,0.206424,0.251919,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,Healthy Control,binary,mlp,Ab raw,0.495867,0.413335,0.621918,0.370479,0.273719,0.266487,...,0.333840,0.270565,0.325159,0.271960,0.176922,0.244656,0.000000,0.000000,0.000000,0.000000
13,Healthy Control,binary,mlp,Demographic,0.483400,0.398750,0.655986,0.357911,0.301397,0.279393,...,0.349699,0.270827,0.346083,0.270965,0.174850,0.246077,0.000000,0.000000,0.000000,0.000000
14,Healthy Control,no-cutoff,mlp,Ab raw,0.535700,0.403428,0.619973,0.367267,0.312387,0.286403,...,0.352646,0.288492,0.346319,0.288512,0.190607,0.267935,0.000000,0.000000,0.000000,0.000000
15,Healthy Control,no-cutoff,mlp,Demographic,0.465200,0.404094,0.676181,0.340198,0.303930,0.276851,...,0.370695,0.290423,0.364508,0.290630,0.197768,0.272004,0.000000,0.000000,0.000000,0.000000
16,Multiple Myeloma,binary,mlp,Ab raw,0.646070,0.318162,0.554716,0.312371,0.430913,0.239578,...,0.415075,0.210117,0.367241,0.216879,0.284159,0.216648,0.193036,0.208291,0.033810,0.110930
17,Multiple Myeloma,binary,mlp,Demographic,0.627095,0.315665,0.575061,0.314948,0.433184,0.238849,...,0.408932,0.212654,0.362861,0.214397,0.285706,0.217180,0.196446,0.216485,0.036191,0.109282
18,Multiple Myeloma,no-cutoff,mlp,Ab raw,0.694260,0.284533,0.510371,0.293177,0.450811,0.232638,...,0.414415,0.204752,0.363287,0.211372,0.284551,0.211632,0.196808,0.205368,0.035677,0.104284
19,Multiple Myeloma,no-cutoff,mlp,Demographic,0.622594,0.324405,0.559589,0.293603,0.429370,0.235248,...,0.402547,0.209165,0.350024,0.214717,0.276248,0.214548,0.190659,0.212111,0.031509,0.105063
20,Transplant,binary,mlp,Ab raw,0.537691,0.373858,0.488890,0.367582,0.251589,0.219368,...,0.208658,0.178453,0.162481,0.167614,0.116611,0.152271,0.053954,0.104502,0.027493,0.076456
21,Transplant,binary,mlp,Demographic,0.502633,0.369290,0.534127,0.371389,0.257053,0.218305,...,0.218928,0.178051,0.164149,0.165244,0.115937,0.151913,0.052400,0.107752,0.026806,0.073531
22,Transplant,no-cutoff,mlp,Ab raw,0.573318,0.348820,0.445617,0.345308,0.274433,0.215471,...,0.216695,0.182055,0.163081,0.167883,0.121611,0.150517,0.063445,0.110236,0.030635,0.081741
23,Transplant,no-cutoff,mlp,Demographic,0.504569,0.365947,0.517544,0.365622,0.257346,0.211533,...,0.207636,0.170043,0.159159,0.156727,0.110314,0.140000,0.057091,0.105937,0.024188,0.071820

In [33]:
agg_df['Train_Timepoint'] = 'Post-B'
agg_df['Test_Timepoint'] = 'Pre-B'

agg_df['Test_Cohort'] = agg_df['cohort']
agg_df['Train_Cohort'] = agg_df['cohort']


    
# counts

def update_usage(row, what):
    cohort = row['cohort']
    return counts[f'{cohort},{what}']

# Apply transformation
for what in ['Train_N_Low', 'Train_N_High', 'Test_N_High', 'Test_N_Low']:
    agg_df[what] = agg_df.apply(lambda z:update_usage(z, what=what), axis=1)
    
    
agg_df = agg_df.rename(columns={
    # 'cohort': 'Train_Cohort', 
    'clf': 'Classifier', 
    'AUC_mean': 'CV_AUC_Mean',
    'AUC_std': 'CV_AUC_SD',
    'Sensitivity at 0.8 Specificity_mean': 'CV_Sen_at_80_Spe_Mean',
    'Sensitivity at 0.8 Specificity_std': 'CV_Sen_at_80_Spe_SD',
    'Low Responders Accuracy_mean': 'CV_Acc_Low_Mean',
    'High Responders Accuracy_mean': 'CV_Acc_High_Mean',
    'Low Responders Accuracy_std': 'CV_Acc_Low_SD',
    'High Responders Accuracy_std': 'CV_Acc_High_SD',
})

def update_usage(row):
    # Start with base usage name
    usage = row['usage']
    setting = row['setting']
    
    
    # Case 1: if usage is "Ab raw"
    
    out = 'Ab_raw'
    
    
    # Case 2: if usage is "Demographic"
    if setting.strip().lower() == 'binary':
        out += '+ Ab_binary'
        
    if usage.strip().lower() == 'demographic':
        out += '+ demographic'
    
    # Case 3: modify further based on 'setting'
    
    if setting.strip().lower() == 'no-cutoff':
        # don't add anything
        pass
    
    return out

# Apply transformation
agg_df['Feature_Set'] = agg_df.apply(update_usage, axis=1)
agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier', 'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]

,Train_Timepoint,Train_Cohort,Train_N_Low,Train_N_High,Feature_Set,Test_Timepoint,Test_Cohort,Test_N_Low,Test_N_High,Classifier,CV_AUC_Mean,CV_AUC_SD,CV_Sen_at_80_Spe_Mean,CV_Sen_at_80_Spe_SD,CV_Acc_Low_Mean,CV_Acc_Low_SD,CV_Acc_High_Mean,CV_Acc_High_SD
0,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw+ Ab_binary,Pre-B,Autoimmune: Other,12.0,62.0,mlp,0.500048,0.209318,0.329333,0.316343,0.527333,0.460929,0.477661,0.432361
1,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw+ Ab_binary+ demographic,Pre-B,Autoimmune: Other,12.0,62.0,mlp,0.499297,0.205470,0.333000,0.325475,0.431667,0.452544,0.567488,0.433237
2,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw,Pre-B,Autoimmune: Other,12.0,62.0,mlp,0.514399,0.213372,0.338667,0.324661,0.540667,0.452499,0.467968,0.421006
3,Post-B,Autoimmune: Other,13.0,67.0,Ab_raw+ demographic,Pre-B,Autoimmune: Other,12.0,62.0,mlp,0.526367,0.208210,0.366000,0.334733,0.455000,0.458264,0.569083,0.431170
4,Post-B,Cancer: Other,8.0,95.0,Ab_raw+ Ab_binary,Pre-B,Cancer: Other,6.0,77.0,mlp,0.515084,0.253889,0.339729,0.421752,0.488713,0.493037,0.507319,0.450962
5,Post-B,Cancer: Other,8.0,95.0,Ab_raw+ Ab_binary+ demographic,Pre-B,Cancer: Other,6.0,77.0,mlp,0.541151,0.261252,0.370203,0.437978,0.445824,0.487861,0.567615,0.432740
6,Post-B,Cancer: Other,8.0,95.0,Ab_raw,Pre-B,Cancer: Other,6.0,77.0,mlp,0.499890,0.250372,0.312641,0.422632,0.490971,0.486152,0.501807,0.437148
7,Post-B,Cancer: Other,8.0,95.0,Ab_raw+ demographic,Pre-B,Cancer: Other,6.0,77.0,mlp,0.514824,0.263442,0.314898,0.422291,0.435666,0.486042,0.565775,0.435092
8,Post-B,HIV,14.0,68.0,Ab_raw+ Ab_binary,Pre-B,HIV,14.0,62.0,mlp,0.584775,0.192545,0.434667,0.299109,0.530667,0.429710,0.528387,0.415201
9,Post-B,HIV,14.0,68.0,Ab_raw+ Ab_binary+ demographic,Pre-B,HIV,14.0,62.0,mlp,0.588697,0.181032,0.425667,0.307946,0.458000,0.429009,0.607487,0.394092
10,Post-B,HIV,14.0,68.0,Ab_raw,Pre-B,HIV,14.0,62.0,mlp,0.600493,0.199487,0.459667,0.310124,0.568667,0.409142,0.530758,0.391694
11,Post-B,HIV,14.0,68.0,Ab_raw+ demographic,Pre-B,HIV,14.0,62.0,mlp,0.589253,0.190955,0.428000,0.310031,0.460333,0.426825,0.619157,0.392899
12,Post-B,Healthy Control,21.0,462.0,Ab_raw+ Ab_binary,Pre-B,Healthy Control,18.0,422.0,mlp,0.652637,0.155438,0.480900,0.277384,0.495867,0.413335,0.621918,0.370479
13,Post-B,Healthy Control,21.0,462.0,Ab_raw+ Ab_binary+ demographic,Pre-B,Healthy Control,18.0,422.0,mlp,0.667502,0.147804,0.507300,0.260896,0.483400,0.398750,0.655986,0.357911
14,Post-B,Healthy Control,21.0,462.0,Ab_raw,Pre-B,Healthy Control,18.0,422.0,mlp,0.686009,0.154698,0.548433,0.276838,0.535700,0.403428,0.619973,0.367267
15,Post-B,Healthy Control,21.0,462.0,Ab_raw+ demographic,Pre-B,Healthy Control,18.0,422.0,mlp,0.673814,0.163420,0.524767,0.285823,0.465200,0.404094,0.676181,0.340198
16,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw+ Ab_binary,Pre-B,Multiple Myeloma,42.0,78.0,mlp,0.682631,0.120401,0.515469,0.244827,0.646070,0.318162,0.554716,0.312371
17,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw+ Ab_binary+ demographic,Pre-B,Multiple Myeloma,42.0,78.0,mlp,0.676443,0.118487,0.496998,0.247714,0.627095,0.315665,0.575061,0.314948
18,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw,Pre-B,Multiple Myeloma,42.0,78.0,mlp,0.674518,0.117310,0.480468,0.250845,0.694260,0.284533,0.510371,0.293177
19,Post-B,Multiple Myeloma,60.0,90.0,Ab_raw+ demographic,Pre-B,Multiple Myeloma,42.0,78.0,mlp,0.656790,0.117761,0.434858,0.263568,0.622594,0.324405,0.559589,0.293603
20,Post-B,Transplant,71.0,67.0,Ab_raw+ Ab_binary,Pre-B,Transplant,50.0,56.0,mlp,0.529069,0.128804,0.327190,0.193219,0.537691,0.373858,0.488890,0.367582
21,Post-B,Transplant,71.0,67.0,Ab_raw+ Ab_binary+ demographic,Pre-B,Transplant,50.0,56.0,mlp,0.533677,0.121870,0.322508,0.204261,0.502633,0.369290,0.534127,0.371389
22,Post-B,Transplant,71.0,67.0,Ab_raw,Pre-B,Transplant,50.0,56.0,mlp,0.519987,0.125438,0.298298,0.189269,0.573318,0.348820,0.445617,0.345308
23,Post-B,Transplant,71.0,67.0,Ab_raw+ demographic,Pre-B,Transplant,50.0,56.0,mlp,0.519356,0.122256,0.309813,0.192527,0.504569,0.365947,0.517544,0.365622

In [34]:
out = agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier',	'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]
out.to_csv(f'final_results_{DIM}d/model_performance_summary_v6_revised.csv')

#### All

In [35]:
pd.concat(
    [pd.read_csv(f'final_results_{DIM}d/model_performance_summary_v1_revised.csv'),
     pd.read_csv(f'final_results_{DIM}d/model_performance_summary_v2_revised.csv'),
     pd.read_csv(f'final_results_{DIM}d/model_performance_summary_v3_revised.csv'),
     pd.read_csv(f'final_results_{DIM}d/model_performance_summary_v4_revised.csv'),
     pd.read_csv(f'final_results_{DIM}d/model_performance_summary_v5_revised.csv'),
     pd.read_csv(f'final_results_{DIM}d/model_performance_summary_v6_revised.csv'),
    ],
     ignore_index=True
).to_csv(f'final_results_{DIM}d/all_final_revised.csv', index=False)

#### Cross cohort

In [8]:
d = {}
for c in COHORTS:
    for cc in COHORTS:
        if c == cc:
            continue
        d[f'{c}-{cc}'] = []

In [13]:
device = 'cuda'
def safe_logit(y, eps=1e-6):
    y = torch.clip(y, eps, 1 - eps)
    return torch.log(y / (1 - y))


for_json = {}
for k, v in results_8_excel.items():
    
    seed, cohort, task, setting, clf, coeffs, usage = re.split(r',\s*(?![^()]*\))', k)
    if clf != 'mlp':
        continue
    if usage != 'Demographic':
        continue
    if setting == 'binary':
        continue
    print(seed, cohort, task, setting, clf, coeffs, usage)
    
    seed = int(seed)
    if setting == 'binary':
        cutoffs = GLOBAL_CUTOFFS
    else:
        cutoffs = None
        
    X, y , emb_list, real_size, encoder = load_6(binary=True, cutoffs=cutoffs)
    
    if 'raw' in usage:
        use_cat = False
    else:
        use_cat = True
    
    if use_cat:
            start_from = len(emb_list)
    else:
        start_from = 11
        
    
    for outer_cohort in COHORTS:
        if outer_cohort == cohort:
            continue
        print(outer_cohort)
        idx = X[:, 0] == outer_cohort
        if (y[idx] == 0).sum() < 5:
            continue
        X_test_tensor = torch.from_numpy(X[idx, start_from:].astype(np.float32))
        y_batch = torch.from_numpy(y[idx]).float()
        
        size = real_size if use_cat else real_size - 1
        m = BottleneckMLP(emb_list, size, start_from, 8, (128, 64, DIM), p=0.2, use_cat=use_cat, binary=True).to(device)
        logits = 0
        
        for fold in range(5):
            m.load_state_dict(v[0][fold])
            m.eval()
            with torch.no_grad():
                logits += safe_logit(m(X_test_tensor.to(device))[0])
            
        logits = logits.detach().cpu() / 5
        y_pred = torch.sigmoid(logits)
        y_pred = (y_pred.reshape(-1) > 0.5).int().cpu()
        # print(yhat)
        # raise
        a_test = (y_pred[y_batch==0] == y_batch[y_batch==0]).float().mean().item() + 1e-20
        b_test = (y_pred[y_batch==1] == y_batch[y_batch==1]).float().mean().item() + 1e-20
        c_test = 2 / ((1/a_test) + 1/b_test)
        # print(y_batch, logits, y_batch.shape, logits.shape, seed, cohort, outer_cohort)
        for_json[f'{cohort}, {outer_cohort}, {seed}'] = (y_batch.cpu().numpy().tolist(), logits.cpu().numpy().tolist())
        # raise
        try:
            auc_test = roc_auc_score(y_batch.cpu().numpy(), logits.cpu().numpy())
        except:
            auc_test = None
        sen_test = []
        spec_test = []
        for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
            sen_, spec_ = at_95(logits.cpu().numpy(), y_batch, t=t)
            sen_test.append(sen_)
            spec_test.append(spec_)
        
        d[f'{cohort}-{outer_cohort}'].append((auc_test, a_test, b_test, c_test, sen_test, spec_test))
        # print('============================================================')
    print('============================================================')

0 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
0 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
0 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
0 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
0 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
0 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
1 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
1 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
1 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
1 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
1 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
1 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
2 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
2 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
2 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
2 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
2 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
2 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
3 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
3 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
3 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
3 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
3 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
3 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
4 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
4 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
4 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
4 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
4 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
4 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
5 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
5 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
5 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
5 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
5 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
5 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
6 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
6 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
6 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
6 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
6 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
6 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
7 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
7 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
7 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
7 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
7 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
7 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
8 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
8 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
8 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
8 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
8 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
8 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
9 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
9 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
9 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
9 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
9 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
9 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
10 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
10 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
10 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
10 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
10 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
10 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
11 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
11 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
11 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
11 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
11 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
11 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
12 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
12 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
12 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
12 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
12 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
12 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
13 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
13 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
13 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
13 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
13 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
13 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
14 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
14 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
14 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
14 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
14 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
14 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
15 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
15 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
15 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
15 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
15 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
15 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
16 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
16 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
16 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
16 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
16 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
16 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
17 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
17 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
17 HIV 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
17 Healthy Control 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
IBD
Multiple Myeloma
Transplant
============================================================
17 Multiple Myeloma 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Transplant
============================================================
17 Transplant 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
============================================================
18 Autoimmune: Other 8 no-cutoff mlp (4, 1) Demographic
Cancer: Other
HIV
Healthy Control
IBD
Multiple Myeloma
Transplant
============================================================
18 Cancer: Other 8 no-cutoff mlp (4, 1) Demographic
Autoimmune: Other
HIV
Healthy Control
IBD
Multiple Myeloma

In [14]:
import json
with open("cross_cohort.json", "w") as f:
    json.dump(for_json, f)

In [ ]:
for c in COHORTS:
    for cc in COHORTS:
        if c == cc:
            continue
        if c == 'IBD' or cc == 'IBD':
            continue
        X, y , emb_list, real_size, encoder = load_6(binary=True, cutoffs=cutoffs)
        idx1 = X[:, 0] == c
        
        idx2 = X[:, 0] == cc
        try:
            # print((y[idx1] == 0).astype(float).sum(), (y[idx1] == 1).astype(float).sum())
            # print((y[idx2] == 0).astype(float).sum(), (y[idx2] == 1).astype(float).sum())
            # print(c, cc, torch.tensor([row[0] for row in d[f'{c}-{cc}'][:]]).mean().item(), torch.tensor([row[0] for row in d[f'{c}-{cc}'][:]]).std().item())
            print(torch.tensor([row[0] for row in d[f'{c}-{cc}'][:]]).std().item())
            # print('-----')
        except:
            pass

In [ ]:

columns = []
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Sensitivity at {t} Specificity')
for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
    columns.append(f'Specificity at {t} Sensitivity')
columns = [
    'Low Responders Accuracy',
    'High Responders Accuracy',
    'Harmonic Mean',
    'AUC'
] + columns


split_pattern = r',\s*(?![^()]*\))'

records = []
for k, v in results_8_excel.items():
    parts = re.split(split_pattern, k)
    seed, cohort, task, setting, clf, coeffs, usage = parts
    records.append({
        'seed': int(seed),
        'cohort': cohort,
        'task': task,
        'setting': setting,
        'clf': clf,
        'coeffs': coeffs,
        'usage': usage,
        **{name: val for name, val in zip(columns, v[-1])}
    })

df = pd.DataFrame(records)

group_cols = ['cohort', 'task', 'setting', 'clf', 'coeffs', 'usage']
metric_cols = columns

agg_df = df.groupby(group_cols)[metric_cols].agg(['mean', 'std']).reset_index()
agg_df.columns = ['_'.join(col).strip('_') for col in agg_df.columns.values]

# print(agg_df)


X, y , emb_list, real_size, encoder = load_6(binary=True, cutoffs=None)
counts = {}
for cohort in COHORTS:
    
    # idx = X[:, 0] == 'Healthy Control'
    idx = X[:, 0] == cohort
    
    all_low_count = (y[idx] == 0).astype(float).sum()
    all_high_count = (y[idx] == 1).astype(float).sum()
    print(all_low_count, all_high_count, cohort)
    counts[f'{cohort},Test_N_Low'] = all_low_count
    counts[f'{cohort},Train_N_Low'] = all_low_count
    counts[f'{cohort},Test_N_High'] = all_high_count
    counts[f'{cohort},Train_N_High'] = all_high_count
counts


agg_df['Train_Timepoint'] = 'Post-B'
agg_df['Test_Timepoint'] = 'Post-B'
agg_df['Test_Cohort'] = agg_df['cohort']
def update_usage(row, what):
    cohort = row['cohort']
    return counts[f'{cohort},{what}']

for what in ['Train_N_Low', 'Train_N_High', 'Test_N_High', 'Test_N_Low']:
    agg_df[what] = agg_df.apply(lambda z:update_usage(z, what=what), axis=1)
    
agg_df = agg_df.rename(columns={
    'cohort': 'Train_Cohort', 
    'clf': 'Classifier', 
    'AUC_mean': 'CV_AUC_Mean',
    'AUC_std': 'CV_AUC_SD',
    'Sensitivity at 0.8 Specificity_mean': 'CV_Sen_at_80_Spe_Mean',
    'Sensitivity at 0.8 Specificity_std': 'CV_Sen_at_80_Spe_SD',
    'Low Responders Accuracy_mean': 'CV_Acc_Low_Mean',
    'High Responders Accuracy_mean': 'CV_Acc_High_Mean',
    'Low Responders Accuracy_std': 'CV_Acc_Low_SD',
    'High Responders Accuracy_std': 'CV_Acc_High_SD',
})

def update_usage(row):
    usage = row['usage']
    setting = row['setting']
    
    # Case 1: if usage is "Ab raw"
    
    out = 'Ab_raw'
    
    # Case 2: if usage is "Demographic"
    if setting.strip().lower() == 'binary':
        out += '+ Ab_binary'
        
    if usage.strip().lower() == 'demographic':
        out += '+ demographic'
    
    # Case 3: modify further based on 'setting'
    
    if setting.strip().lower() == 'no-cutoff':
        # don't add anything
        pass
    
    return out

# Apply transformation
agg_df['Feature_Set'] = agg_df.apply(update_usage, axis=1)
out = agg_df[['Train_Timepoint', 'Train_Cohort', 'Train_N_Low', 'Train_N_High', 'Feature_Set', 'Test_Timepoint', 'Test_Cohort', 'Test_N_Low' ,'Test_N_High', 'Classifier',	'CV_AUC_Mean', 'CV_AUC_SD',	'CV_Sen_at_80_Spe_Mean', 'CV_Sen_at_80_Spe_SD', 'CV_Acc_Low_Mean', 'CV_Acc_Low_SD',	'CV_Acc_High_Mean',	'CV_Acc_High_SD']]
out

#### Vaccine type

In [ ]:
metrics = {}
# dim = 16
device = 'cuda' if torch.cuda.is_available() else 'cpu'

for k, v in results_6_excel.items():
    seed, task, setting, clf, coeffs, usage = re.split(r',\s*(?![^()]*\))', k)
    if clf != 'mlp':
        continue
    if usage != 'Demographic':
        continue

    if setting == 'binary':
        continue

    seed = int(seed)
    if setting == 'binary':
        cutoffs = GLOBAL_CUTOFFS
    else:
        cutoffs = None

    if 'raw' in usage:
        use_cat = False
    else:
        use_cat = True
    if use_cat:
            start_from = len(emb_list)
    else:
        start_from = 11
        
        
    
    X, y , emb_list, real_size, encoder = load_6(binary=True, cutoffs=cutoffs)
    df = pd.read_csv('Leidos_data_98_Abs_with_clinical_features_v3.csv')
    df = pd.read_csv('Leidos_data_98_Abs_with_clinical_features_v3.csv')
    df['V0_Vaccine'] = df['V0_Vaccine'].fillna(df['B0_Vaccine'])
    df['B0_Vaccine'] = df['B0_Vaccine'].fillna(df['V0_Vaccine'])
    d_pid = dict(zip(df['PID'], df['B0_Vaccine']))
    vaccine_type = np.array([d_pid[i] for i in pid])
    size = real_size if use_cat else real_size - 1
    
    en = {}
    for k_cohort, v_cohort in (X[:, [0, 5]]):
        en[k_cohort] = v_cohort
     
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
    
    
    for_stratify = y
    for fold, (train_idx, test_idx) in enumerate(skf.split(X, for_stratify), start=0):
        #################################################### Dataset
        X_test = X[test_idx]
        y_test = y[test_idx]
        vtype_test = vaccine_type[test_idx]
        
        X_test_tensor = torch.from_numpy(X_test[:, start_from:].astype(np.float32))
        y_test_tensor = torch.from_numpy(y_test).float()
        
        test_loader = DataLoader(TensorDataset(X_test_tensor, y_test_tensor),
                                 batch_size=len(X_test_tensor), shuffle=False)
        
        m = BottleneckMLP(emb_list, size, start_from, 8, (128, 64, DIM), p=0.2, use_cat=use_cat, binary=True).to(device)
        
        m.load_state_dict(v[0][fold])
        
        
        for v_type in ['Moderna', 'Pfizer', 'Others']:
            print(seed, fold, v_type)
            for x_batch, y_batch in test_loader:
                pass

            if v_type in ['Moderna', 'Pfizer']:
                
                index = vtype_test == v_type
            else:
                index1 = vtype_test != 'Pfizer'
                index2 = vtype_test != 'Moderna'
                index = index1 & index2
            
            # print(X_test[index].shape)
            # raise
            
            
            
            if (y_batch[index] == 0).float().sum() < 1:
                print(cohort, fold, seed, 'not enough negative samples')
                continue
            if clf == 'mlp':
                with torch.no_grad():
                    m.eval()
                    logits, two_d = m(x_batch[index].to(device))
            
            if 1:
                if clf == 'mlp':
                    y_pred = (logits.reshape(-1) > 0.5).int().cpu()
                
                a_test = (y_pred[y_batch[index]==0] == y_batch[index][y_batch[index]==0]).float().mean().item() + 1e-20
                b_test = (y_pred[y_batch[index]==1] == y_batch[index][y_batch[index]==1]).float().mean().item() + 1e-20
                c_test = 2 / ((1/a_test) + 1/b_test)
                
                try:
                    auc_test = roc_auc_score(y_batch[index].cpu().numpy(), logits.cpu().numpy())
                except:
                    auc_test = None
                sen_test = []
                spec_test = []
                for t in [0.75, 0.8, 0.85, 0.9, 0.95]:
                    sen_, spec_ = at_95(logits.cpu().numpy(), y_batch[index], t=t)
                    sen_test.append(sen_)
                    spec_test.append(spec_)
                    
            
            metrics[f'{seed}, {fold}, {v_type}, {clf}, {setting}, {usage}'] = ([a_test, b_test, c_test, auc_test, *spec_test, *sen_test])                        
    
        # print('-----------------')

In [ ]:
# X, y , pid, emb_list, real_size, encoder = load_6(binary=True, cutoffs=cutoffs, include_pid=True)
res_pfizer = []
res_moderna = []
res_others = []
an = []
for k, v in metrics.items():
    sd, fld, vt, cclf, cut, usg = k.split(', ')
    # print(sd, fld, vt, cclf, cut, usg)
    an.append(v[3])
    if vt == 'Pfizer':
        res_pfizer.append(v[3])
    elif vt == 'Moderna':
        res_moderna.append(v[3])
    elif vt == 'Others':
        res_others.append(v[3])
np.array(res_pfizer).mean(), np.array(res_moderna).mean(), np.array(res_others).mean(), np.array(an).mean()

In [ ]:
res_others

In [ ]:
index1 = vtype_test != 'Pfizer'
index2 = vtype_test != 'Moderna'
index1.astype(float).sum(), index2.astype(float).sum(), (index1 & index2).astype(float).sum()

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder


def load_2(
    binary=True, 
    cutoffs=None, 
    include_pid=False, 
    path='Leidos_data_98_Abs_with_clinical_features_v2.csv',
    exclude_hiv=True
):
    df = pd.read_csv(path)
    
    group = 'B0_Group'
    which = group.split('_')[0]
    pre = df[df[group] == f'Pre {which}']
    post = df[df[group] == f'Post {which}']
    
    result = pd.merge(pre, post, on="PID", how="inner")
        
    if exclude_hiv:
            x_cols = ['Cohort_x'] + [i for i in result.columns[7:] if ('_x' in i and 'HIV' not in i)]
    else:
        x_cols = ['Cohort_x'] + [i for i in result.columns[7:] if '_x' in i] 
    
    data = result[x_cols + ['Vaccine_Response_class_y'] + ['Vaccine_Response_raw_y']].dropna()
    X = data[x_cols].values
    
    if cutoffs is not None:
        thresholds = []
        cutoff_cols = list(map(lambda z: z[:-2], x_cols))[6:]
        for c in cutoff_cols:
            thresholds.append(cutoffs[c])
        thresholds = np.array(thresholds)

        I = (X[:, 6:] >= thresholds).astype(float)
        h = np.maximum(0.0, X[:, 6:] - thresholds)
        X_aug = np.concatenate([X, I, h], axis=1)
        X = X_aug
        
    if binary:
        y = (data['Vaccine_Response_class_y'] == 'High').astype(int).values
    else:
        y = data['Vaccine_Response_raw_y'].values
    
    
    cat_cols = [0, 2, 3, 4, 5]
    X_cat = X[:, cat_cols]
    X_real = np.delete(X, cat_cols, axis=1)
    
    encoder = OrdinalEncoder()
    X_cat_encoded = encoder.fit_transform(X_cat)
    
    X_processed = np.hstack([X_cat, X_cat_encoded, X_real])
    

    emb_list = list(X_processed[:, 5:10].max(0).astype(int) + 1)
    real_size = X_processed.shape[1] - 10
    
    if not include_pid:
        return X_processed, y, emb_list, real_size, encoder
    else:
        a = result[['PID'] + x_cols + ['Vaccine_Response_class_y'] + ['Vaccine_Response_raw_y']].dropna()
        return X_processed, y, a['PID'].values, emb_list, real_size, encoder



def load_6(
    binary=True, 
    cutoffs=None, 
    include_pid=False, 
    path='Leidos_data_98_Abs_with_clinical_features_v2.csv',
    exclude_hiv=True
):
    df = pd.read_csv(path)
    group = 'B0_Group'
    which = group.split('_')[0]
        
    post = df[df[group] == f'Post {which}']
    
    data = post[['Cohort'] + list(post.columns[5:])].dropna()
    
    if exclude_hiv:
        x_cols = [i for i in ['Cohort'] + list(data.columns[3:]) if 'HIV' not in i]
    else:
        x_cols = ['Cohort'] + list(data.columns[3:]) 
    
    X = data[x_cols].values
    if cutoffs is not None:
        
        thresholds = []
        cutoff_cols = list(map(lambda z: z, x_cols))[6:]
        
        for c in cutoff_cols:
            thresholds.append(cutoffs[c])
        thresholds = np.array(thresholds)

        I = (X[:, 6:] >= thresholds).astype(float)                # same shape [batch_size, d]
        h = np.maximum(0.0, X[:, 6:] - thresholds)     # same shape
        X_aug = np.concatenate([X, I, h], axis=1)
        X = X_aug
    
    if binary:
        y = (data['Vaccine_Response_class'] == 'High').astype(int).values
    else:
        y = data['Vaccine_Response_raw'].values
    
    cat_cols = [0, 2, 3, 4, 5]
    
    X_cat = X[:, cat_cols]
    X_real = np.delete(X, cat_cols, axis=1)

    encoder = OrdinalEncoder()
    X_cat_encoded = encoder.fit_transform(X_cat)
    
    X_processed = np.hstack([X_cat, X_cat_encoded, X_real])
    
    
    emb_list = list(X_processed[:, 5:10].max(0).astype(int) + 1)
    real_size = X_processed.shape[1] - 10
    

    if not include_pid:
        return X_processed, y, emb_list, real_size, encoder
    else:
        a = post[['PID'] + ['Cohort'] + list(post.columns[5:])].dropna()
        return X_processed, y, a['PID'].values, emb_list, real_size, encoder


X_before, y , emb_list, real_size, encoder = load_6(binary=True, cutoffs=None)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

def load_2(
    binary=True, 
    cutoffs=None, 
    include_pid=False, 
    path='Leidos_data_98_Abs_with_clinical_features_v3.csv',
    exclude_hiv=True,
    include_all_vaccines=True
):
    df = pd.read_csv(path)
    
    # Filter for Pfizer/Moderna if the flag is False
    if not include_all_vaccines:
        valid_vax = ['Pfizer', 'Moderna']
        df = df[df['V0_Vaccine'].isin(valid_vax) | df['B0_Vaccine'].isin(valid_vax)]
        
    group = 'B0_Group'
    which = group.split('_')[0]
    pre = df[df[group] == f'Pre {which}']
    post = df[df[group] == f'Post {which}']
    
    result = pd.merge(pre, post, on="PID", how="inner")
    
    # 1. Dynamically identify antibody columns
    ab_start_col = 'A.calcoaceticus LysM_x'
    ab_start_idx = list(result.columns).index(ab_start_col)
    ab_cols = [c for c in result.columns[ab_start_idx:] if '_x' in c]
    
    if exclude_hiv:
        ab_cols = [c for c in ab_cols if 'HIV' not in c]
        
    # 2. Explicitly define metadata features to use (Vaccine columns removed from here)
    cat_col_names = ['Cohort_x', 'Age_Group_x', 'Age_Group_1_x', 'Sex_x', 'Race_x']
    real_col_names = ['Age_x']
    
    # 3. Build x_cols deterministically
    x_cols = cat_col_names + real_col_names + ab_cols
    
    data = result[x_cols + ['Vaccine_Response_class_y', 'Vaccine_Response_raw_y', 'PID']].dropna()
    X = data[x_cols].values
    
    # 4. Calculate dynamic indices based on list lengths
    n_cat = len(cat_col_names)
    n_real = len(real_col_names)
    abs_start_idx = n_cat + n_real  
    
    if cutoffs is not None:
        thresholds = []
        cutoff_cols = [c[:-2] for c in ab_cols] 
        for c in cutoff_cols:
            thresholds.append(cutoffs[c])
        thresholds = np.array(thresholds)

        I = (X[:, abs_start_idx:] >= thresholds).astype(float)
        h = np.maximum(0.0, X[:, abs_start_idx:] - thresholds)
        X_aug = np.concatenate([X, I, h], axis=1)
        X = X_aug
        
    if binary:
        y = (data['Vaccine_Response_class_y'] == 'High').astype(int).values
    else:
        y = data['Vaccine_Response_raw_y'].values
    
    cat_cols_idx = list(range(n_cat))
    
    X_cat = X[:, cat_cols_idx]
    X_real = np.delete(X, cat_cols_idx, axis=1)
    
    encoder = OrdinalEncoder()
    X_cat_encoded = encoder.fit_transform(X_cat)
    
    X_processed = np.hstack([X_cat, X_cat_encoded, X_real])
    
    emb_list = list(X_processed[:, n_cat : n_cat*2].max(0).astype(int) + 1)
    real_size = X_processed.shape[1] - (n_cat * 2)
    
    if not include_pid:
        return X_processed, y, emb_list, real_size, encoder
    else:
        return X_processed, y, data['PID'].values, emb_list, real_size, encoder


def load_6(
    binary=True, 
    cutoffs=None, 
    include_pid=False, 
    path='Leidos_data_98_Abs_with_clinical_features_v3.csv',
    exclude_hiv=True,
    include_all_vaccines=True 
):
    df = pd.read_csv(path)
    
    # Filter for Pfizer/Moderna if the flag is False
    if not include_all_vaccines:
        valid_vax = ['Pfizer', 'Moderna']
        df = df[df['V0_Vaccine'].isin(valid_vax) | df['B0_Vaccine'].isin(valid_vax)]
        
    group = 'B0_Group'
    which = group.split('_')[0]
        
    post = df[df[group] == f'Post {which}']
    
    # 1. Dynamically identify antibody columns
    ab_start_col = 'A.calcoaceticus LysM'
    ab_start_idx = list(post.columns).index(ab_start_col)
    ab_cols = list(post.columns[ab_start_idx:])
    
    if exclude_hiv:
        ab_cols = [c for c in ab_cols if 'HIV' not in c]
        
    # 2. Explicitly define metadata features to use (Vaccine columns removed from here)
    cat_col_names = ['Cohort', 'Age_Group', 'Age_Group_1', 'Sex', 'Race']
    real_col_names = ['Age']
    
    # 3. Build x_cols deterministically
    x_cols = cat_col_names + real_col_names + ab_cols
    
    data = post[x_cols + ['Vaccine_Response_class', 'Vaccine_Response_raw', 'PID']].dropna()
    X = data[x_cols].values
    
    # 4. Calculate dynamic indices based on list lengths
    n_cat = len(cat_col_names)
    n_real = len(real_col_names)
    abs_start_idx = n_cat + n_real
    
    if cutoffs is not None:
        thresholds = []
        for c in ab_cols:
            thresholds.append(cutoffs[c])
        thresholds = np.array(thresholds)

        I = (X[:, abs_start_idx:] >= thresholds).astype(float)
        h = np.maximum(0.0, X[:, abs_start_idx:] - thresholds)
        X_aug = np.concatenate([X, I, h], axis=1)
        X = X_aug
    
    if binary:
        y = (data['Vaccine_Response_class'] == 'High').astype(int).values
    else:
        y = data['Vaccine_Response_raw'].values
    
    cat_cols_idx = list(range(n_cat))
    
    X_cat = X[:, cat_cols_idx]
    X_real = np.delete(X, cat_cols_idx, axis=1)

    encoder = OrdinalEncoder()
    X_cat_encoded = encoder.fit_transform(X_cat)
    
    X_processed = np.hstack([X_cat, X_cat_encoded, X_real])
    
    emb_list = list(X_processed[:, n_cat : n_cat*2].max(0).astype(int) + 1)
    real_size = X_processed.shape[1] - (n_cat * 2)
    
    if not include_pid:
        return X_processed, y, emb_list, real_size, encoder
    else:
        return X_processed, y, data['PID'].values, emb_list, real_size, encoder
        
X_after, y , emb_list, real_size, encoder = load_6(binary=True, cutoffs=None, include_all_vaccines=False)

In [ ]:
X_after.shape, X_before.shape